FROM @BASE_IMAGE@
LABEL maintainer="Matthieu Kermagoret <mkermagoret@centreon.com>"

# Run distribution-dependent installation.
COPY dependencies/@VERSION@/dependencies.@DISTRIB@.txt /tmp/dependencies.txt
COPY dependencies/@VERSION@/install.@DISTRIB@.sh /tmp/install.sh

# Copy centreon internal certificate
COPY ca-centreon-internal.pem /tmp/ca-centreon-internal.pem

RUN /tmp/install.sh
