# Currently supports only CentOS 7 / PHP 7.1.

FROM ci.int.centreon.com:5000/mon-build-dependencies-3.4:centos7
LABEL maintainer="Matthieu Kermagoret <mkermagoret@centreon.com>"

RUN yum install centos-release-scl
ENV PATH=$PATH:/opt/rh/rh-php71/root/usr/bin
