---
  - jenkins_job:
      name: centreon-repo-19.10-testing
      config: "{{ lookup('file', 'repo-testing.xml.in') | regex_replace('@SERIE@', '19.10') }}"
      user: "{{ jenkins_user }}"
      password: "{{ jenkins_password }}"
