name: rpm-sign-in-docker
description: Run step in docker container
inputs:
  script_name:
    description: "script_name"
    required: true
  image_name:
    description: "image_name"
    required: true
  image_version:
    description: "image_version"
    required: true
  centreon_pat:
    description: "Secret"
    required: false
  registry_url:
    description: Docker registry url
    required: true
  registry_username:
    description: Docker registry username
    required: true
  registry_password:
    description: Docker registry password
    required: true
  registry_private_username:
    description: Docker private registry username
    required: true
  registry_private_token:
    description: Docker private registry token
    required: true
  params:
    description: "params for script"
    required: false
runs:
  using: "composite"
  steps:
    - name: Login to Registry
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ${{ inputs.registry_url }}
        username: ${{ inputs.registry_private_username }}
        password: ${{ inputs.registry_private_password }}

    # REMOVE ME LATER
    - run: docker pull ${{ inputs.registry_url }}/${{ inputs.image_name }}:${{ inputs.image_version}}
      shell: bash

    - run: docker run -i -e TOKEN=${{ inputs.centreon_pat }} --entrypoint /src/.github/scripts/${{ inputs.script_name }}.sh -v "$PWD:/src" ${{ inputs.registry_url }}/${{ inputs.image_name }}:${{ inputs.image_version}} ${{ inputs.params }}
      shell: bash
