# Base information.
FROM ci.int.centreon.com:5000/mon-web-18.10:@DISTRIB@
MAINTAINER Matthieu Kermagoret <mkermagoret@centreon.com>

# Install package.
RUN yum --disablerepo='*' --enablerepo='centreon-internal*' clean all
RUN yum install -y centreon-bam-server

# Install license file.
COPY bam/merethis_lic.zl /usr/share/centreon/www/modules/centreon-bam-server/license/merethis_lic.zl

# Install module in Centreon.
COPY web/18.10/install-centreon-module.php /tmp/install-centreon-module.php
COPY bam/18.10/install.sh /tmp/install.sh
RUN chmod +x /tmp/install-centreon-module.php /tmp/install.sh
RUN /tmp/install.sh
