# Base information.
FROM ci.int.centreon.com:5000/mon-dependencies-@VERSION@:@DISTRIB@
LABEL maintainer="Matthieu Kermagoret <mkermagoret@centreon.com>"

# Install all build dependencies of Centreon components.
COPY build-dependencies/@VERSION@/build-dependencies.@DISTRIB@.txt /tmp/build-dependencies.txt
COPY unittest/@VERSION@/install.@DISTRIB@.sh /tmp/install.sh
RUN /tmp/install.sh

# Install unit tests scripts.
COPY unittest/unittest-phing.sh /usr/local/bin/unittest-phing
COPY unittest/unittest-engine.sh /usr/local/bin/unittest-engine
COPY unittest/unittest-middleware.sh /usr/local/bin/unittest-middleware
