@Library('centreon-shared-library') _

pipeline {
    agent none
    triggers {
        cron('0 0 * * *')
    }
    stages {
      stage('Launch Centreon Tests') {
        agent any
        // when { anyOf { branch 'dev-21.10.x'; branch '21.10.x'; branch 'robot-nightly-21.10.x' } }
        // ${GIT_BRANCH}
        environment { 
                      JENKINS_USERNAME = "Service-Account-CI" 
                      BRANCHE= "dev-21.10.x" 
                      TEST = sh 'aws ssm get-parameter --name service-account-ci-token --output text --query Parameter.Value --region eu-west-1'
                      }
        steps {
            sh 'TEST=$(aws ssm get-parameter --name service-account-ci-token --output text --query Parameter.Value --region eu-west-1)'
            sh 'printenv'
            sh 'docker run -i --entrypoint /src/ci/scripts/collect-test-robot.sh -v "$PWD:/src" registry.centreon.com/centreon-collect-centos7-dependencies:21.10 $JENKINS_USERNAME $TEST $BRANCHE'
            robot outputPath: 'tests', logFileName: 'log.html', outputFileName: 'output.xml', reportFileName: 'report.html', passThreshold: 100, unstableThreshold: 75.0
        }
        post { always { cleanWs() }}
      }
    }
}
