@Library('centreon-shared-library') _

pipeline {

    agent none
    triggers {
        cron('0 0 * * *')
    }
    stages {
      stage('Launch Centreon Tests') {
          agent any
          // when { branch 'master'; branch 'develop'; branch 'COPS-824-cicd-create-pipeline-centreon-test-on-centreon-collect'
          //        beforeAgent true }
          steps {
            sh 'docker run -i --entrypoint /src/ci/scripts/collect-test-robot.sh -v "$PWD:/src" registry.centreon.com/centreon-collect-centos7-dependencies:22.04'
            robot outputPath: 'tests', logFileName: 'log.html', outputFileName: 'output.xml', reportFileName: 'report.html', passThreshold: 100, unstableThreshold: 75.0
          }
          post { always { cleanWs() }}
      }
    }
}
