@Library('centreon-shared-library') _

pipeline {

    agent none
    triggers {
        cron('0 0 * * *')
    }
    stages {
    stage('Launch Centreon Tests') {
      agent any
      //when { anyOf { branch 'dev-22.04.x'; branch '22.04.x'} }
      environment { 
        JENKINS_USERNAME = "Service-Account-CI" 
        BRANCHE = "dev-22.04.x"
        JENKINS_TOKEN =  sh (
          script: 'aws ssm get-parameter --name service-account-ci-token --output text --query Parameter.Value --region eu-west-1',
          returnStdout: true)
      }
      steps {
          sh 'docker run -i --entrypoint /src/ci/scripts/collect-test-robot.sh -v "$PWD:/src" registry.centreon.com/centreon-collect-centos7-dependencies:22.04 $JENKINS_USERNAME $JENKINS_TOKEN $BRANCHE'
          robot outputPath: 'tests', logFileName: 'log.html', outputFileName: 'output.xml', reportFileName: 'report.html', passThreshold: 100, unstableThreshold: 75.0
      }
      post { always { cleanWs() }}
    }
  }
}
