FROM @BASE_IMAGE@
LABEL maintainer="Matthieu Kermagoret <mkermagoret@centreon.com>"

# Run distribution-dependent installation.
COPY build-dependencies/@VERSION@/build-dependencies.@DISTRIB@.txt /tmp/build-dependencies.txt
COPY build-dependencies/@VERSION@/install.@DISTRIB@.sh /tmp/install.sh
RUN /tmp/install.sh
