import json
import re
from subprocess import getoutput

from robot.api import logger


def ctn_files_contain_same_json(file_e: str, file_b: str):
    """
    ctn_files_contain_same_json

    Given the two files produced by the Engine-side and Broker-side stream
    connectors, this function checks that both contain the SAME set of events.

    The comparison is order-insensitive: the Engine-side muxer and the
    Broker-side muxer can legitimately observe the same events in a different
    order (e.g. during a Broker restart, the BBDO3 centralized-configuration
    resync re-orders the replayed events relative to the Engine's local log
    messages). Only the multiset of events must match, not their ordering.

    Matching is done first by md5 (identical serialized events) and then, for
    the remainder, by a field-by-field comparison that tolerates small float
    differences (e.g. execution_time, latency).

    Args:
        file_e (str): The log file produced by Engine
        file_b (str): The log file produced by Broker

    Returns:
        A boolean that is True on success, False otherwise.
    """
    from collections import defaultdict, deque

    new_inst = '{"_type": 4294901762, "category": 65535, "element": 2, "broker_id": 1, "broker_name": "",' \
               '"enabled": True, "poller_id": 1, "poller_name": "Central"}'.upper()

    # "<date>: INFO: <type> <md5> <json>"
    r = re.compile(r"INFO:\s+\d+\s+([0-9a-f]+)\s+(\{.*\})\s*$")

    def parse(fname):
        """List of (md5, parsed_json) for the relevant events, skipping the
        new instance event and the pb_stop (131081) messages that cannot cross
        the network."""
        events = []
        for line in open(fname):
            m = r.search(line)
            if m is None:
                continue
            md5, js = m.group(1), m.group(2)
            if js.upper() == new_inst:
                continue
            parsed = json.loads(js)
            if parsed.get('_type') == 131081:  # local::pb_stop
                continue
            events.append((md5, parsed))
        return events

    ev1 = parse(file_e)
    ev2 = parse(file_b)

    # Pass 1: cancel out events with an identical md5 (order-insensitive).
    pool2 = defaultdict(deque)
    for md5, parsed in ev2:
        pool2[md5].append(parsed)
    leftover1 = []
    for md5, parsed in ev1:
        if pool2[md5]:
            pool2[md5].popleft()
        else:
            leftover1.append(parsed)
    leftover2 = [parsed for dq in pool2.values() for parsed in dq]

    # Pass 2: match the remainder field-by-field, tolerating small float diffs.
    def same_event(a, b):
        if a.keys() != b.keys():
            return False
        for k in a:
            va, vb = a[k], b[k]
            if isinstance(va, float) or isinstance(vb, float):
                try:
                    if abs(va - vb) > 0.1:
                        return False
                except TypeError:
                    return False
            elif va != vb:
                return False
        return True

    unmatched1 = []
    for a in leftover1:
        for i, b in enumerate(leftover2):
            if same_event(a, b):
                leftover2.pop(i)
                break
        else:
            unmatched1.append(a)

    if unmatched1 or leftover2:
        for a in unmatched1[:5]:
            logger.console(f"Event in '{file_e}' has no counterpart in '{file_b}':\n{a}")
        for b in leftover2[:5]:
            logger.console(f"Event in '{file_b}' has no counterpart in '{file_e}':\n{b}")
        return False
    return True


def ctn_files_contain_same_md5_1(file_e: str, file_b: str):

    getoutput("awk '{{print $8}}' {0} > {0}.md5".format(file_e))
    getoutput("awk '{{print $8}}' {0} > {0}.md5".format(file_b))

    f1 = open("{}.md5".format(file_e))
    content1 = f1.readlines()

    f2 = open("{}.md5".format(file_b))
    content2 = f2.readlines()

    idx1 = 0
    idx2 = 0

    while idx1 < len(content1) and idx2 < len(content2):
        if content1[idx1] == "test1.lua\n":
            idx1 += 1

        if content2[idx2] == "test.lua\n":
            idx2 += 1
            if content2[idx2] == "055b1a6348a16305474b60de439a0efd\n":
                idx2 += 1
            else:
                return False

        if content1[idx1] == content2[idx2]:
            idx1 += 1
            idx2 += 1
        else:
            print("We have to improve comparaison here")
            return False
    return idx1 == len(content1) and idx2 == len(content2)

##
# @brief Given two files generated by a stream connector, this function checks
# that no events except special ones are sent / replayed twice.
#
# @param str The first file name
# @param str The second file name
#
# @return A boolean True on success


def ctn_check_multiplicity_when_broker_restarted(eng_file: str, broker_file: str):
    f1 = open(eng_file)
    content1 = f1.readlines()
    f2 = open(broker_file)
    content2 = f2.readlines()

    r = re.compile(r".* INFO: ([0-9]+)\s+([0-9a-f]+)\s(.*)$")

    def create_md5_list(content):
        lst = dict()
        typ = dict()
        for l in content:
            m = r.match(l)
            if m:
                type, md5, js = int(m.group(1)), m.group(2), m.group(3)
                if type not in [65544,          # host check
                                196613,         # index mapping => produced on new conf
                                196619,         # pb index mapping => produced on new conf
                                65555,          # service check
                                0x1001a,        # responsive_instance => periodically generated by cbd
                                0x10027,        # pb_host_check
                                0x10028,        # pb_service_check
                                0x1002e,        # pb_responsive_instance
                                0x10036         # pb_instance_configuration
                                ]:
                    if md5 in lst:
                        lst[md5] += 1
                    else:
                        lst[md5] = 1
                        typ[md5] = type
        return lst, typ

    lst1, typ1 = create_md5_list(content1)
    lst2, typ2 = create_md5_list(content2)

    res1 = set(lst1.values())
    res2 = set(lst2.values())
    if len(res1) != 1 or len(res2) != 1:
        for k in lst1:
            if lst1[k] != 1:
                logger.console(
                    "In lst1: Bad {} {} with type {:x}".format(k, lst1[k], typ1[k]))
        for k in lst2:
            if lst2[k] != 1:
                logger.console(
                    "In lst2: Bad {} {} with type {:x}".format(k, lst2[k], typ2[k]))
    return len(res1) == 1 and len(res2) == 1

def ctn_check_multiplicity_when_engine_restarted(file1: str, file2: str):
    """
    ctn_check_multiplicity_when_engine_restarted

    Given two files generated by a stream connector, this function checks
    that no events except special ones are sent / replayed twice.

    Args:
        str The first file name
        str The second file name

    Returns:
        A boolean True on success
    """

    f1 = open(file1)
    content1 = f1.readlines()
    f2 = open(file2)
    content2 = f2.readlines()

    r = re.compile(r".* INFO: ([0-9]+)\s+([0-9a-f]+)\s(.*)$")

    def create_md5_list(content):
        lst = dict()
        typ = dict()
        for l in content:
            m = r.match(l)
            if m:
                type, md5, js = int(m.group(1)), m.group(2), m.group(3)
                """
                 Are removed:
                   * instance configurations
                   * modules
                   * host checks (they can be done several times
                   * host and service events are also configuration events, so sent each time engine is restarted.
                   * local::pb_stop (this one is special and cannot pass through
                     a network).
                """
                if type not in [65544,          # host check
                                65554,          # module
                                65561,          # instance configuration
                                65555,          # service check
                                0x10017,        # service
                                0x1000c,        # host
                                0x1001b,        # pb_service
                                0x1001e,        # pb_host
                                0x1002b,        # pb_module
                                0x10025,        # pb_custom_variable
                                0x10027,        # pb_host_check
                                0x10028,        # pb_service_check
                                0x10036,        # pb_instance_configuration
                                0x90001,        # local::pb_stop
                                ]:
                    if md5 in lst:
                        lst[md5] += 1
                    else:
                        lst[md5] = 1
                        typ[md5] = type
        return lst, typ

    lst1, typ1 = create_md5_list(content1)
    lst2, typ2 = create_md5_list(content2)

    res1 = set(lst1.values())
    res2 = set(lst2.values())
    if len(res1) != 1 or len(res2) != 1:
        for k in lst1:
            if lst1[k] != 1:
                logger.console(
                    "In lst1: Bad {} {} with type {:x}".format(k, lst1[k], typ1[k]))
        for k in lst2:
            if lst2[k] != 1:
                logger.console(
                    "In lst2: Bad {} {} with type {:x}".format(k, lst2[k], typ2[k]))
    return len(res1) == 1 and len(res2) == 1

