x-defaults: &defaults
  environment:
    TZ: "${TZ:-America/Toronto}"
    DEBUG: "${DEBUG:-false}"

services:
  centengine:
    <<: *defaults
    image: docker.centreon.com/centreon/centreon-engine-bookworm:${TAG:-latest}
    container_name: centpoller
    hostname: centengine
    restart: always
    volumes:
      - poller-engine:/etc/centreon-engine
      - poller-broker:/etc/centreon-broker
      - poller-centcmd:/var/lib/centreon-engine/rw
      - poller-centlog:/var/log/centreon-engine

  gorgone:
    environment:
      TZ: "${TZ:-America/Toronto}"
      DEBUG: "${DEBUG:-false}"
      TYPE: poller
      POLLER_ID: "${POLLER_ID}"
      CENTRAL_ADDRESS: "${CENTRAL_ADDRESS}"
      CENTRAL_PORT: "${CENTRAL_PORT:-443}"
      GORGONE_TOKEN: "${GORGONE_TOKEN}"
    image: docker.centreon.com/centreon/centreon-gorgone-bookworm:${TAG:-latest}
    container_name: centpoller-gorgone
    hostname: centgorgone
    restart: always
    volumes:
      - poller-etc:/etc/centreon/
      - poller-engine:/etc/centreon-engine
      - poller-broker:/etc/centreon-broker
      - poller-centcmd:/var/lib/centreon-engine/rw
      - poller-centcache:/var/cache/centreon/
      - poller-gorgone-data:/var/lib/centreon-gorgone/

volumes:
  poller-etc:
  poller-engine:
  poller-broker:
  poller-centcmd:
  poller-centlog:
  poller-centcache:
  poller-gorgone-data:
