x-defaults: &defaults
  environment:
    TZ: "${TZ:-America/Toronto}"
    DEBUG: "${DEBUG:-false}"

services:
  centengine:
    <<: *defaults
    image: docker.centreon.com/centreon/centreon-engine-bookworm:${TAG:-latest}
    container_name: centpoller
    hostname: centengine
    restart: always
    volumes:
      - poller-engine:/etc/centreon-engine
      - poller-broker:/etc/centreon-broker
      - poller-centcmd:/var/lib/centreon-engine/rw
      - poller-centlog:/var/log/centreon-engine

  gorgone:
    environment:
      TZ: "${TZ:-America/Toronto}"
      DEBUG: "${DEBUG:-false}"
      TYPE: poller
      POLLER_ID: "${POLLER_ID}"
      CENTRAL_ADDRESS: "${CENTRAL_ADDRESS}"
      CENTRAL_PORT: "${CENTRAL_PORT:-443}"
      GORGONE_TOKEN: "${GORGONE_TOKEN}"
      WEB_API_USERNAME: "${WEB_API_USERNAME}"
      WEB_API_PASSWORD: "${WEB_API_PASSWORD}"
    image: docker.centreon.com/centreon/centreon-gorgone-bookworm:${TAG:-latest}
    container_name: centpoller-gorgone
    hostname: centgorgone
    restart: always
    volumes:
      - poller-etc:/etc/centreon/
      - poller-engine:/etc/centreon-engine
      - poller-broker:/etc/centreon-broker
      - poller-centcmd:/var/lib/centreon-engine/rw
      - poller-centcache:/var/cache/centreon/
      - poller-gorgone-data:/var/lib/centreon-gorgone/
      - poller-snmp-traps:/etc/snmp/centreon_traps

  centreon-vmware:
    <<: *defaults
    image: connector-vmware:local
    container_name: centreon-vmware
    hostname: centreon-vmware
    restart: always
    volumes:
      - poller-etc:/etc/centreon/
      - poller-engine:/etc/centreon-engine:ro

  snmptrapd:
    <<: *defaults
    image: docker.centreon.com/centreon/centreon-snmptrapd-bookworm:${TAG:-latest}
    container_name: centpoller-snmptrapd
    hostname: snmptrapd
    restart: always
    environment:
      TZ: "${TZ:-America/Toronto}"
      DEBUG: "${DEBUG:-false}"
      SNMP_COMMUNITY: "${SNMP_COMMUNITY:-public}"
    volumes:
      - poller-snmp-spool:/var/spool/centreontrapd
    ports:
      - "162:162/udp"
    cap_add:
      - NET_BIND_SERVICE

  centreontrapd:
    <<: *defaults
    image: docker.centreon.com/centreon/centreon-centreontrapd-bookworm:${TAG:-latest}
    container_name: centpoller-centreontrapd
    hostname: centreontrapd
    restart: always
    environment:
      TZ: "${TZ:-America/Toronto}"
      DEBUG: "${DEBUG:-false}"
      TRAP_SDB_PATH: /etc/snmp/centreon_traps/centreontrapd.sdb
    volumes:
      - poller-snmp-spool:/var/spool/centreontrapd
      - poller-snmp-traps:/etc/snmp/centreon_traps
      - poller-centcmd:/var/lib/centreon-engine/rw
    depends_on:
      - snmptrapd

volumes:
  poller-etc:
  poller-engine:
  poller-broker:
  poller-centcmd:
  poller-centlog:
  poller-centcache:
  poller-gorgone-data:
  poller-snmp-spool:
  poller-snmp-traps:
