# Base information.
FROM registry.centreon.com/mon-web-21.10:@DISTRIB@
MAINTAINER Matthieu Kermagoret <mkermagoret@centreon.com>

# Install Centreon repositories.
RUN curl -o centreon-release.rpm "http://yum-1.centreon.com/standard/21.10/el7/stable/noarch/RPMS/centreon-release-21.10-1.el7.centos.noarch.rpm"
RUN yum install --nogpgcheck centreon-release.rpm
RUN curl -o centreon-release-business.rpm http://yum-1.centreon.com/centreon-business/1a97ff9985262bf3daf7a0919f9c59a6/21.10/el7/stable/noarch/RPMS/centreon-business-release-21.10-1.el7.centos.noarch.rpm
RUN yum install --nogpgcheck centreon-release-business.rpm
RUN yum-config-manager --enable 'centreon-testing*'
RUN yum-config-manager --enable 'centreon-unstable*'
RUN yum-config-manager --enable 'centreon-business-testing'
RUN yum-config-manager --enable 'centreon-business-unstable'
RUN yum install -y centreon-bam-server && \
    yum clean all

# Install license file.
COPY bam/bam.license.ppd /etc/centreon/license.d/bam.license

# Install module in Centreon.
COPY web/21.10/install-centreon-module.php /tmp/install-centreon-module.php
COPY bam/21.10/install.sh /tmp/install.sh
RUN chmod +x /tmp/install-centreon-module.php /tmp/install.sh
RUN /tmp/install.sh
