# Base information.
FROM ci.int.centreon.com:5000/mon-web-19.4:@DISTRIB@
LABEL maintainer="Kevin Duret <kduret@centreon.com>"

# Install repository.
COPY repo/centreon-internal.repo /etc/yum.repos.d/centreon-internal.repo

# Install package.
RUN yum install -y centreon-auto-discovery-server && \
    rm -f /etc/yum.repos.d/centreon-internal.repo && \
    yum clean all

# Install module in Centreon.
COPY web/19.4/install-centreon-module.php /tmp/install-centreon-module.php
COPY autodisco/19.4/install.sh /tmp/install.sh
RUN chmod +x /tmp/install-centreon-module.php /tmp/install.sh && \
    /tmp/install.sh
