FROM centos:7

# fix locale
RUN yum -y upgrade && yum -y update && \
    yum -y install perl-Thread-Queue \
    perl-devel \
    perl-Data-Dumper \
    perl-ExtUtils-MakeMaker \
    perl-ExtUtils-Embed.noarch \
    redhat-lsb \
    rh-python38 \
    perl-Ext* \
    perl-App-FatPacker \
    perl-File-Copy-Recursive \
    perl-JSON \
    gettext \
    expect \
    perl-XML-SAX \
    rpm-build \
    unzip \
    ShellCheck

WORKDIR /src
