FROM debian:buster
RUN apt-get -y update && \
    apt-get -y install curl
RUN curl http://ftp.fr.debian.org/debian/pool/main/c/cmake/cmake_3.18.4-2+deb11u1~bpo10+1_amd64.deb --output cmake_3.18.4-2+deb11u1~bpo10+1_amd64.deb
RUN curl http://ftp.fr.debian.org/debian/pool/main/c/cmake/cmake-data_3.18.4-2+deb11u1~bpo10+1_all.deb --output cmake-data_3.18.4-2+deb11u1~bpo10+1_all.deb
RUN curl http://ftp.fr.debian.org/debian/pool/main/d/dwz/dwz_0.13-5~bpo10+1_amd64.deb --output dwz_0.13-5~bpo10+1_amd64.deb
RUN apt-get -y update && \
    apt-get -y install cmake \
    gcc \
    g++ \
    pkg-config \
    ninja-build \
    libmariadb3 \
    librrd-dev \
    libgnutls28-dev \
    ninja-build \
    liblua5.3-dev \
    python3 \
    python3-pip \
    libperl-dev \
    libgcrypt20-dev \
    dh-make \
    aptitude \
    lintian \
    pbuilder \
    quilt \
    git-buildpackage \
    debmake \
    devscripts \
    fakeroot \
    dwz \
    locales && \
    rm -rf /var/lib/apt/lists/* && \
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
RUN dpkg -i cmake_3.18.4-2+deb11u1~bpo10+1_amd64.deb cmake-data_3.18.4-2+deb11u1~bpo10+1_all.deb
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3 get-pip.py
RUN pip3 install conan
RUN ln -s /usr/local/bin/conan /usr/bin/conan
RUN rm -rf ~/.conan/profiles/default
COPY conanfile.txt .
RUN cat conanfile.txt
RUN conan install . -s compiler.cppstd=14 -s compiler.libcxx=libstdc++11 --build='missing'
WORKDIR /src


