# Base information.
FROM registry.centreon.com/mon-web-3.4:@DISTRIB@
MAINTAINER Matthieu Kermagoret <mkermagoret@centreon.com>

# Install repository.
COPY repo/centreon-internal.repo /etc/yum.repos.d/centreon-internal.repo

# Install package.
RUN yum install -y centreon-bam-server && \
    rm -f /etc/yum.repos.d/centreon-internal.repo && \
    yum clean all

# Install license file.
COPY bam/3.4/merethis_lic.zl /usr/share/centreon/www/modules/centreon-bam-server/license/merethis_lic.zl

# Install module in Centreon.
COPY web/3.4/install-centreon-module.php /tmp/install-centreon-module.php
COPY bam/3.4/install.sh /tmp/install.sh
RUN chmod +x /tmp/install-centreon-module.php /tmp/install.sh
RUN /tmp/install.sh
