---
  - jenkins_job:
      name: mon-containers-build-dependencies-18.10-centos7
      config: "{{ lookup('file', 'mon-containers-build-dependencies.xml.in') | regex_replace('@SERIE@', '18.10') | regex_replace('@DISTRIB@', 'centos7')}}"
      user: "{{ jenkins_user }}"
      password: "{{ jenkins_password }}"
