# Base information.
FROM registry.centreon.com/mon-web-20.10:@DISTRIB@
LABEL maintainer="Kevin Duret <kduret@centreon.com>"

# Install package.
RUN yum install centreon-auto-discovery-server centreon-license-manager && \
    yum clean all

# Install module in Centreon.
COPY web/20.10/install-centreon-module.php /tmp/install-centreon-module.php
COPY autodisco/20.10/install.sh /tmp/install.sh
RUN chmod +x /tmp/install-centreon-module.php /tmp/install.sh && \
    /tmp/install.sh

# License.
COPY ppm/epp.license.offline /etc/centreon/license.d/epp.license
