# Base information.
FROM registry.centreon.com/mon-web-21.04:@DISTRIB@
MAINTAINER Matthieu Kermagoret <mkermagoret@centreon.com>


# Install package.
RUN yum install -y centreon-bam-server && \
    yum clean all

# Install license file.
COPY bam/bam.license.ppd /etc/centreon/license.d/bam.license

# Install module in Centreon.
COPY web/21.04/install-centreon-module.php /tmp/install-centreon-module.php
COPY bam/21.04/install.sh /tmp/install.sh
RUN chmod +x /tmp/install-centreon-module.php /tmp/install.sh
RUN /tmp/install.sh
