# Base information.
FROM registry.centreon.com/mon-web-20.10:@DISTRIB@
MAINTAINER Matthieu Kermagoret <mkermagoret@centreon.com>

# Install repository.
COPY repo/centreon-internal.repo /etc/yum.repos.d/centreon-internal.repo

# Install package.
RUN yum install -y centreon-bam-server && \
    rm -f /etc/yum.repos.d/centreon-internal.repo && \
    yum clean all

# Install license file.
COPY bam/bam.license.ppd /etc/centreon/license.d/bam.license

# Install module in Centreon.
COPY web/20.10/install-centreon-module.php /tmp/install-centreon-module.php
COPY bam/20.10/install.sh /tmp/install.sh
RUN chmod +x /tmp/install-centreon-module.php /tmp/install.sh
RUN /tmp/install.sh
