FROM @BASE_IMAGE@
LABEL maintainer="Matthieu Kermagoret <mkermagoret@centreon.com>"

# Run distribution-dependent installation.
COPY build-dependencies/3.4/build-dependencies.@DISTRIB@.txt /tmp/build-dependencies.txt
COPY repo/centreon-internal.repo.in /tmp/centreon-internal.repo.in
COPY build-dependencies/3.4/install.@DISTRIB@.sh /tmp/install.sh
RUN /tmp/install.sh
