debian/extra/centreon-broker/cbd.service    lib/systemd/system
debian/tmp-centreon-collect/usr/bin/cbd    usr/sbin
debian/tmp-centreon-collect/usr/bin/cbwd   usr/sbin
debian/tmp-centreon-collect/etc/centreon-broker/central-broker.json    etc/centreon-broker
debian/tmp-centreon-collect/etc/centreon-broker/central-rrd.json    etc/centreon-broker
debian/tmp-centreon-collect/etc/centreon-broker/watchdog.json    etc/centreon-broker
