ARG REGISTRY_URL

FROM ${REGISTRY_URL}/debian:bookworm

ARG VERSION

COPY . /tmp/collect

RUN bash -e <<EOF

VERSION_CODENAME=\$(
    . /etc/os-release
    echo \$VERSION_CODENAME
)

echo "deb https://packages.centreon.com/apt-standard-${VERSION}-stable/ \$VERSION_CODENAME main" | tee -a /etc/apt/sources.list.d/centreon-stable.list
echo "deb https://packages.centreon.com/apt-standard-${VERSION}-testing/ \$VERSION_CODENAME main" | tee -a /etc/apt/sources.list.d/centreon-testing.list
echo "deb https://packages.centreon.com/apt-standard-${VERSION}-unstable/ \$VERSION_CODENAME main" | tee -a /etc/apt/sources.list.d/centreon-unstable.list
wget -O- https://packages.centreon.com/api/security/keypair/APT-GPG-KEY/public | gpg --dearmor | tee /etc/apt/trusted.gpg.d/centreon.gpg > /dev/null 2>&1

apt-get update

apt-get -y install \
    ca-certificates \
    curl \
    gcc \
    g++ \
    gdb \
    git \
    mariadb-server \
    openssh-server \
    libmariadb3 \
    librrd8 \
    libgnutlsxx30 \
    liblua5.3 \
    python3 \
    python3-dev \
    python3-pip \
    libperl-dev \
    libgcrypt20 \
    aptitude \
    strace \
    locales \
    rrdtool \
    rrdcached \
    zstd \
    psmisc \
    sudo \
    perl-base \
    wget

apt-get clean

localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

pip3 install --break-system-packages -U robotframework robotframework-databaselibrary robotframework-httpctrl robotframework-examples pymysql python-dateutil psutil
pip3 install --break-system-packages grpcio grpcio_tools py-cpuinfo cython unqlite gitpython boto3 robotframework-requests

cd /tmp/collect

.github/scripts/collect-prepare-test-robot.sh mariadb

/bin/rm -rf /tmp/collect

EOF

