ARG REGISTRY_URL

FROM ${REGISTRY_URL}/almalinux:8

RUN bash -e <<EOF

# Base dnf configuration.
echo 'http_caching=none' >> /etc/yum.conf && \
echo 'assumeyes=1' >> /etc/yum.conf && \
sed -i 's/best=True/best=False/g' /etc/dnf/dnf.conf && \
dnf install -y dnf-plugins-core
dnf config-manager --set-enabled powertools

dnf install -y epel-release

echo '[goreleaser]
name=GoReleaser
baseurl=https://repo.goreleaser.com/yum/
enabled=1
gpgcheck=0' | tee /etc/yum.repos.d/goreleaser.repo

curl -LsS "https://r.mariadb.com/downloads/mariadb_repo_setup" | bash -s -- --skip-maxscale --os-type=rhel --os-version=8 --mariadb-server-version="mariadb-10.5"

dnf install -y cmake \
    gcc \
    gcc-c++ \
    gdb \
    gettext \
    git \
    ninja-build \
    openssh-server \
    MariaDB-devel \
    MariaDB-shared \
    MariaDB-client \
    MariaDB-compat \
    MariaDB-common \
    MariaDB-server \
    gnutls-devel \
    libgcrypt-devel \
    lua-devel \
    make \
    perl-ExtUtils-Embed.noarch \
    python38 \
    python38-pip \
    perl-Thread-Queue \
    redhat-lsb \
    rrdtool-devel \
    selinux-policy-devel \
    yum-utils \
    perl-interpreter \
    zstd \
    nfpm-2.41.1 \
    openssl-devel \
    libssh2-devel \
    libcurl-devel \
    zlib-devel \
    sudo

dnf update libarchive

git clone --depth 1 -b 2024.01.12 https://github.com/Microsoft/vcpkg.git
./vcpkg/bootstrap-vcpkg.sh
mkdir /src

EOF

COPY vcpkg.json /src
COPY overlays /overlays
COPY custom-triplets /custom-triplets

RUN bash -e <<EOF

export VCPKG_ROOT=/vcpkg
export PATH=\$VCPKG_ROOT:\$PATH

/vcpkg/vcpkg install --overlay-triplets=custom-triplets --triplet x64-linux-release --vcpkg-root vcpkg --x-wait-for-lock --x-manifest-root=/src --x-install-root=vcpkg_installed --overlay-ports=overlays

EOF

WORKDIR /src
