ARG REGISTRY_URL

FROM ${REGISTRY_URL}/debian:bullseye

RUN bash -e <<EOF

apt-get update

apt-get -y install cmake \
    git \
    curl \
    gcc \
    g++ \
    gdb \
    pkg-config \
    ninja-build \
    mariadb-server \
    openssh-server \
    libmariadb3 \
    librrd-dev \
    libgnutls28-dev \
    liblua5.3-dev \
    python3 \
    python3-pip \
    libperl-dev \
    libgcrypt20-dev \
    aptitude \
    git-buildpackage \
    fakeroot \
    strace \
    locales \
    rrdtool \
    rrdcached \
    zstd \
    libssl-dev \
    libssh2-1-dev \
    zlib1g-dev \
    zip \
    sudo

echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
apt-get update
apt-get install -y nfpm

apt-get clean

localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

git clone -b 2024.01.12 https://github.com/Microsoft/vcpkg.git
./vcpkg/bootstrap-vcpkg.sh
mkdir /src

EOF

COPY vcpkg.json /src
COPY overlays /overlays

RUN bash -e <<EOF

vcpkg/vcpkg install --triplet x64-linux --vcpkg-root vcpkg --x-wait-for-lock --x-manifest-root=/src --x-install-root=build/vcpkg_installed --overlay-ports=overlays

EOF

WORKDIR /src
