ARG REGISTRY_URL

FROM ${REGISTRY_URL}/centreon-collect-alma9-test
#FROM docker.centreon.com/centreon/centreon-collect-alma9-test

COPY . /tmp/collect

RUN <<EOF

cd /tmp/collect

.github/scripts/collect-prepare-test-robot.sh mariadb

EOF

