ARG REGISTRY_URL

FROM ${REGISTRY_URL}/ubuntu:jammy

#FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

COPY . /tmp/collect

RUN bash -e <<EOF

apt-get update

apt-get install -y --no-install-recommends tzdata

apt-get -y install aptitude \
    curl \
    fakeroot \
    gdb \
    git \
    git-buildpackage \
    libgcrypt20 \
    libgnutls30 \
    libmariadb3 \
    libperl-dev \
    libssh2-1 \
    locales \
    mariadb-server \
    openssl \
    python3 \
    python3-pip \
    rrdtool \
    strace \
    sudo \
    zip \
    zstd \
    perl-base

apt-get clean

localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

pip3 install -U robotframework robotframework-databaselibrary robotframework-httpctrl robotframework-examples pymysql python-dateutil psutil
pip3 install grpcio grpcio_tools py-cpuinfo cython unqlite gitpython boto3 robotframework-requests

cd /tmp/collect

.github/scripts/collect-prepare-test-robot.sh mariadb

/bin/rm -rf /tmp/collect

EOF
