ARG REGISTRY_URL

FROM ${REGISTRY_URL}/almalinux:9

COPY . /tmp/collect

RUN <<EOF

# Base dnf configuration.
echo 'http_caching=none' >> /etc/yum.conf
echo 'assumeyes=1' >> /etc/yum.conf
sed -i 's/best=True/best=False/g' /etc/dnf/dnf.conf
dnf install -y dnf-plugins-core
dnf config-manager --set-enabled crb

dnf install -y epel-release

echo '[goreleaser]
name=GoReleaser
baseurl=https://repo.goreleaser.com/yum/
enabled=1
gpgcheck=0' | tee /etc/yum.repos.d/goreleaser.repo

dnf install -y     gcc \
    gcc-c++ \
    gdb \
    git \
    openssh-server \
    mariadb-server \
    mariadb \
    gnutls \
    libgcrypt \
    libssh2 \
    lua \
    perl-ExtUtils-Embed.noarch \
    python3 \
    python3-devel \
    python3-pip \
    perl-Thread-Queue \
    rrdtool \
    perl \
    procps-ng \
    zstd \
    psmisc \
    sudo

echo "install robot and dependencies"

pip3 install -U robotframework robotframework-databaselibrary robotframework-httpctrl robotframework-examples pymysql python-dateutil psutil
pip3 install grpcio grpcio_tools py-cpuinfo cython unqlite gitpython boto3

cd /tmp/collect

.github/scripts/collect-prepare-test-robot.sh mariadb

cd

/bin/rm -rf /tmp/collect

EOF

