ARG REGISTRY_URL=docker.io

FROM ${REGISTRY_URL}/almalinux:9

ARG CENTREON_VERSION

RUN bash -c <<EOF

dnf install -y dnf-plugins-core zstd mariadb iproute epel-release procps lsof
dnf config-manager --set-enabled crb
dnf config-manager --add-repo https://packages.centreon.com/rpm-standard/${CENTREON_VERSION}/el9/centreon-${CENTREON_VERSION}.repo
dnf install -y python3.11 python3.11-pip
pip3.11 install robotframework robotframework-examples robotframework-databaselibrary pymysql robotframework-requests robotframework-jsonlibrary


dnf clean all

EOF
