ARG REGISTRY_URL

FROM ${REGISTRY_URL}/almalinux:9

RUN <<EOF

# Base dnf configuration.
echo 'http_caching=none' >> /etc/yum.conf
echo 'assumeyes=1' >> /etc/yum.conf
sed -i 's/best=True/best=False/g' /etc/dnf/dnf.conf
dnf install -y dnf-plugins-core
dnf config-manager --set-enabled crb

dnf install -y epel-release

echo '[goreleaser]
name=GoReleaser
baseurl=https://repo.goreleaser.com/yum/
enabled=1
gpgcheck=0' | tee /etc/yum.repos.d/goreleaser.repo

dnf --best install -y cmake \
    gcc \
    gcc-c++ \
    gettext \
    git \
    ninja-build \
    openssh-server \
    mariadb-server \
    mariadb \
    gnutls-devel \
    libgcrypt-devel \
    lua-devel \
    make \
    perl-ExtUtils-Embed.noarch \
    python3 \
    python3-pip \
    perl-Thread-Queue \
    rpm-build \
    rrdtool-devel \
    selinux-policy-devel \
    yum-utils \
    perl-interpreter \
    rpm-build \
    procps-ng \
    zstd \
    nfpm-2.41.1 \
    sudo

# TEMPORARY PYTHON UPGRADE TO 3.18 TO HELP WITH DATA_FILTER ISSUE
dnf upgrade -y python3

pip3 install conan==1.64.0 --prefix=/usr --upgrade
rm -rf ~/.conan/profiles/default

EOF

COPY conanfile.txt .

RUN <<EOF

cat conanfile.txt
conan install . -s compiler.cppstd=14 -s compiler.libcxx=libstdc++11 --build=missing

EOF

WORKDIR /src
