ARG REGISTRY_URL

FROM ${REGISTRY_URL}/almalinux:8 AS centreon_collect_packaging

RUN bash -e <<EOF

# Base dnf configuration
sed -i 's/best=True/best=False/g' /etc/dnf/dnf.conf
echo 'install_weak_deps=False' >> /etc/dnf/dnf.conf

dnf install -y dnf-plugins-core
dnf config-manager --set-enabled powertools
dnf install -y epel-release

echo '[goreleaser]
name=GoReleaser
baseurl=https://repo.goreleaser.com/yum/
enabled=1
gpgcheck=0' | tee /etc/yum.repos.d/goreleaser.repo

dnf install --best -y \
    git \
    lua-devel \
    make \
    selinux-policy-devel \
    yum-utils \
    perl-ExtUtils-Embed \
    perl-HTTP-Daemon-SSL \
    perl-interpreter \
    perl-JSON \
    perl-Thread-Queue \
    procps-ng \
    nfpm-2.41.1 \
    sudo \
    wget \
    zstd

dnf update -y libarchive

dnf clean all

EOF

FROM centreon_collect_packaging AS centreon_collect_packaging_vcpkg

RUN bash -e <<EOF

dnf install --best -y \
    gcc \
    gcc-c++ \
    libstdc++-static \
    gdb \
    gettext \
    gnutls-devel \
    libcurl-devel \
    libgcrypt-devel \
    libssh2-devel \
    mariadb \
    mariadb-connector-c-devel \
    ninja-build \
    openssl-devel \
    python3 \
    rrdtool-devel \
    zlib-devel


dnf clean all

wget https://github.com/Kitware/CMake/releases/download/v4.3.3/cmake-4.3.3-linux-\$(arch).sh
mkdir -p /opt/cmake-4.3.3 
bash cmake-4.3.3-linux-\$(arch).sh --skip-license --prefix=/opt/cmake-4.3.3
rm -f cmake-4.3.3-linux-\$(arch).sh

# sccache, used as compiler launcher by the CI builds (checksums of the v0.18.0 release assets).
case \$(arch) in
  x86_64) SCCACHE_SHA256=45f1447fbe231e3037bde351ef70677dd212216c8d62ae7ca409fecc4d6acc89 ;;
  aarch64) SCCACHE_SHA256=2b3284d5da3b46a47dc4229e75bb7b88ac4aa99c8d754fb7d2f84997e5a4354a ;;
esac
SCCACHE_DIR_NAME=sccache-v0.18.0-\$(arch)-unknown-linux-musl
wget -q https://github.com/mozilla/sccache/releases/download/v0.18.0/\$SCCACHE_DIR_NAME.tar.gz -O /tmp/sccache.tar.gz
echo "\$SCCACHE_SHA256  /tmp/sccache.tar.gz" | sha256sum -c -
tar xzf /tmp/sccache.tar.gz -C /tmp
mv /tmp/\$SCCACHE_DIR_NAME/sccache /usr/bin/sccache
rm -rf /tmp/sccache.tar.gz /tmp/\$SCCACHE_DIR_NAME

EOF

COPY vcpkg.json /root/vcpkg.json
COPY overlays /overlays
COPY custom-triplets /custom-triplets

RUN bash -e <<EOF

git clone --depth 1 -b 2026.05.25 https://github.com/Microsoft/vcpkg.git
#jobs have to share all cpus of the host but see all cpus
#so, if we not limit concurrency, each job will start ntotal_cpu+1 gcc
export VCPKG_MAX_CONCURRENCY=8
export VCPKG_FORCE_SYSTEM_BINARIES=1
./vcpkg/bootstrap-vcpkg.sh -disableMetrics

export VCPKG_ROOT=/vcpkg
export PATH=\$VCPKG_ROOT:/opt/cmake-4.3.3/bin:\$PATH

mkdir /src
cp /root/vcpkg.json /src/vcpkg.json

/vcpkg/vcpkg install \
  --clean-after-build \
  --overlay-triplets=custom-triplets \
  --triplet x64-linux \
  --vcpkg-root vcpkg \
  --x-wait-for-lock \
  --x-manifest-root=/src \
  --x-install-root=vcpkg_installed \
  --overlay-ports=overlays

EOF

WORKDIR /src
