ARG REGISTRY_URL

FROM ${REGISTRY_URL}/debian:bookworm

COPY . /tmp/collect

RUN bash -e <<EOF

apt-get update

apt-get -y install curl \
    aptitude \
    g++ \
    gcc \
    gdb \
    git \
    libgcrypt20 \
    libgnutlsxx30 \
    libhttp-daemon-ssl-perl \
    libjson-perl \
    liblua5.3 \
    libmariadb3 \
    libperl-dev \
    librrd8 \
    locales \
    mariadb-server \
    openssh-server \
    openssl \
    psmisc \
    python3 \
    python3-dev \
    python3-pip \
    rrdcached \
    rrdtool \
    strace \
    sudo \
    zstd \
    perl-base

apt-get clean

localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

pip3 install --break-system-packages -U robotframework robotframework-databaselibrary robotframework-httpctrl robotframework-examples pymysql python-dateutil psutil
pip3 install --break-system-packages grpcio grpcio_tools py-cpuinfo cython unqlite gitpython boto3 robotframework-requests

cd /tmp/collect

.github/scripts/collect-prepare-test-robot.sh mariadb

/bin/rm -rf /tmp/collect

EOF

