ARG REGISTRY_URL

FROM ${REGISTRY_URL}/debian:bullseye
#FROM debian:bullseye

RUN <<EOF

apt-get update

apt-get -y install curl \
    gcc \
    g++ \
    gdb \
    mariadb-server \
    openssh-server \
    libmariadb3 \
    librrd8 \
    libgnutlsxx28 \
    liblua5.3 \
    python3 \
    python3-dev \
    python3-pip \
    libperl-dev \
    libgcrypt20 \
    aptitude \
    strace \
    locales \
    rrdtool \
    rrdcached \
    zstd \
    sudo

echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
apt-get update
apt-get install -y nfpm

apt-get clean

localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py

pip3 install -U robotframework robotframework-databaselibrary robotframework-httpctrl robotframework-examples pymysql python-dateutil psutil
pip3 install grpcio grpcio_tools py-cpuinfo cython unqlite gitpython boto3

EOF

