ARG REGISTRY_URL

FROM ${REGISTRY_URL}/almalinux:8

COPY . /tmp/collect

# Base dnf configuration
sed -i 's/best=True/best=False/g' /etc/dnf/dnf.conf
echo 'install_weak_deps=False' >> /etc/dnf/dnf.conf

dnf install -y dnf-plugins-core
dnf config-manager --set-enabled powertools

dnf install -y epel-release

echo '[goreleaser]
name=GoReleaser
baseurl=https://repo.goreleaser.com/yum/
enabled=1
gpgcheck=0' | tee /etc/yum.repos.d/goreleaser.repo

curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup \
  | bash -s -- --os-type=rhel --skip-maxscale --skip-check-installed --os-version=8 --mariadb-server-version="mariadb-10.11"

dnf --best install -y \
    gcc \
    gcc-c++ \
    git \
    gnutls \
    iproute \
    libgcrypt \
    lua \
    mariadb-connector-c \
    mariadb-server \
    mariadb \
    openssh-server \
    python3.11 \
    python3-devel \
    python3.11-pip \
    perl-interpreter \
    procps-ng \
    psmisc \
    perl-HTTP-Daemon-SSL \
    perl-JSON \
    perl-Thread-Queue \
    python3-setuptools \
    rrdtool \
    tcpdump \
    sudo \
    zstd


dnf clean all

echo "install robot and dependencies"
pip3.11 install -U setuptools wheel
#we fix 7.4.2 version due to a bug in 7.5 version of Grep File
pip3.11 install -U robotframework==7.4.2 robotframework-databaselibrary robotframework-httpctrl robotframework-examples pymysql python-dateutil psutil
pip3.11 install grpcio grpcio_tools py-cpuinfo cython gitpython boto3 robotframework-requests PyJWT

cd /tmp/collect

.github/scripts/collect-prepare-test-robot.sh mariadb

/bin/rm -rf /tmp/collect

EOF
