ARG REGISTRY_URL

FROM ${REGISTRY_URL}/almalinux:8

RUN <<EOF

# Base dnf configuration.
echo 'http_caching=none' >> /etc/yum.conf && \
echo 'assumeyes=1' >> /etc/yum.conf && \
sed -i 's/best=True/best=False/g' /etc/dnf/dnf.conf && \
dnf install -y dnf-plugins-core
dnf config-manager --set-enabled powertools

dnf install -y epel-release

echo '[goreleaser]
name=GoReleaser
baseurl=https://repo.goreleaser.com/yum/
enabled=1
gpgcheck=0' | tee /etc/yum.repos.d/goreleaser.repo

curl -LsS "https://r.mariadb.com/downloads/mariadb_repo_setup" | bash -s -- --os-type=rhel --os-version=8 --mariadb-server-version="mariadb-10.5" --skip-maxscale
dnf --best install -y cmake \
    gcc \
    gcc-c++ \
    gdb \
    gettext \
    git \
    ninja-build \
    openssh-server \
    MariaDB-devel \
    MariaDB-shared \
    MariaDB-client \
    MariaDB-compat \
    MariaDB-common \
    MariaDB-server \
    gnutls-devel \
    libgcrypt-devel \
    lua-devel \
    make \
    perl-open.noarch \
    perl-ExtUtils-Embed.noarch \
    python38 \
    python38-pip \
    perl-Thread-Queue \
    redhat-lsb \
    rpm-build \
    rrdtool-devel \
    selinux-policy-devel \
    yum-utils \
    perl-interpreter \
    rpm-build \
    zstd \
    nfpm-2.41.1 \
    sudo

dnf update libarchive

pip3 install conan==1.64.0 --prefix=/usr --upgrade
rm -rf ~/.conan/profiles/default

EOF

COPY conanfile.txt .

RUN <<EOF

cat conanfile.txt
conan install . -s compiler.cppstd=17 -s compiler.libcxx=libstdc++11 --build=missing

EOF

WORKDIR /src
