ARG REGISTRY_URL

FROM ${REGISTRY_URL}/debian:bullseye


COPY . /tmp/collect

RUN <<EOF

apt-get update

apt-get -y install curl \
    gcc \
    g++ \
    gdb \
    git \
    mariadb-server \
    openssh-server \
    libmariadb3 \
    librrd8 \
    libgnutlsxx28 \
    liblua5.3 \
    python3 \
    python3-dev \
    python3-pip \
    libperl-dev \
    libgcrypt20 \
    aptitude \
    strace \
    locales \
    rrdtool \
    rrdcached \
    zstd \
    psmisc \
    sudo

localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py

pip3 install -U robotframework robotframework-databaselibrary robotframework-httpctrl robotframework-examples pymysql python-dateutil psutil
pip3 install grpcio grpcio_tools py-cpuinfo cython unqlite gitpython boto3


cd /tmp/collect

.github/scripts/collect-prepare-test-robot.sh mariadb

/bin/rm -rf /tmp/collect

EOF

