ARG REGISTRY_URL

FROM ${REGISTRY_URL}/almalinux:8

COPY . /tmp/collect

RUN bash -e <<EOF

# Base dnf configuration.
echo 'http_caching=none' >> /etc/yum.conf && \
echo 'assumeyes=1' >> /etc/yum.conf && \
sed -i 's/best=True/best=False/g' /etc/dnf/dnf.conf && \
dnf install -y dnf-plugins-core
dnf config-manager --set-enabled powertools

dnf install -y epel-release

echo '[goreleaser]
name=GoReleaser
baseurl=https://repo.goreleaser.com/yum/
enabled=1
gpgcheck=0' | tee /etc/yum.repos.d/goreleaser.repo

curl -LsS "https://r.mariadb.com/downloads/mariadb_repo_setup" | bash -s -- --os-type=rhel --os-version=8 --mariadb-server-version="mariadb-10.5" --skip-maxscale

dnf module enable python38

dnf --best install -y \
    gcc \
    gcc-c++ \
    gdb \
    git \
    openssh-server \
    mariadb-server \
    mariadb \
    gnutls \
    libgcrypt \
    lua \
    perl-ExtUtils-Embed \
    python38 \
    python38-devel \
    python38-pip \
    perl-Thread-Queue \
    rrdtool \
    perl-interpreter \
    procps-ng \
    zstd \
    psmisc \
    sudo

dnf clean all

echo "install robot and dependencies"

pip3 install -U robotframework robotframework-databaselibrary robotframework-httpctrl robotframework-examples pymysql python-dateutil psutil
pip3 install grpcio grpcio_tools py-cpuinfo cython gitpython boto3 robotframework-requests PyJWT

cd /tmp/collect

.github/scripts/collect-prepare-test-robot.sh mariadb

/bin/rm -rf /tmp/collect

EOF
