ARG REGISTRY_URL

FROM ${REGISTRY_URL}/debian:bullseye

RUN <<EOF

apt-get update

apt-get -y install cmake \
    curl \
    gcc \
    g++ \
    gdb \
    pkg-config \
    ninja-build \
    mariadb-server \
    openssh-server \
    libmariadb3 \
    librrd-dev \
    libgnutls28-dev \
    liblua5.3-dev \
    python3 \
    python3-pip \
    libperl-dev \
    libgcrypt20-dev \
    dh-make \
    aptitude \
    lintian \
    pbuilder \
    quilt \
    git-buildpackage \
    debmake \
    devscripts \
    fakeroot \
    strace \
    locales \
    rrdtool \
    rrdcached \
    zstd \
    sudo \
    perl-base

echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
apt-get update
apt-get install -y nfpm=2.41.1

apt-get clean

localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py
pip3 install conan==1.64.0
ln -s /usr/local/bin/conan /usr/bin/conan
rm -rf ~/.conan/profiles/default

EOF

COPY conanfile.txt .

RUN <<EOF

cat conanfile.txt
conan install . -s compiler.cppstd=17 -s compiler.libcxx=libstdc++11 --build='missing'

EOF

WORKDIR /src
