ARG REGISTRY_URL

#FROM ${REGISTRY_URL}/debian:bullseye
FROM debian:bullseye

COPY build_my_host/bin/centengine /usr/sbin/centengine
COPY build_my_host/bin/centreon_connector_perl /usr/lib/centreon-connector/centreon_connector_perl
COPY build_my_host/bin/centreon_connector_ssh /usr/lib/centreon-connector/centreon_connector_ssh
COPY build_my_host/lib/libcentreon_clib.so /usr/lib/
COPY build_my_host/lib/externalcmd.so /usr/lib/centreon-engine/externalcmd.so
COPY build_my_host/lib/cbmod.so /usr/lib/nagios/cbmod.so
COPY build_my_host/lib/10-neb.so /usr/share/centreon/lib/centreon-broker/
COPY build_my_host/lib/50-tcp.so /usr/share/centreon/lib/centreon-broker/
COPY build_my_host/lib/70-lua.so /usr/share/centreon/lib/centreon-broker/
COPY build_my_host/lib/15-stats.so /usr/share/centreon/lib/centreon-broker/
COPY build_my_host/lib/60-tls.so /usr/share/centreon/lib/centreon-broker/

RUN <<EOF

useradd  -r centreon-engine

apt update && apt install -y lsb-release ca-certificates apt-transport-https software-properties-common wget gnupg2

apt install libuuid-perl

#centreon repo
echo "deb https://packages.centreon.com/apt-standard-23.10-stable/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/centreon.list
echo "deb https://packages.centreon.com/apt-plugins-stable/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/centreon-plugins.list

#repo key
wget -O- https://apt-key.centreon.com | gpg --dearmor | tee /etc/apt/trusted.gpg.d/centreon.gpg > /dev/null 2>&1
apt update

apt install -y    \
    lua50 \
    nagios-nrpe-plugin \
    monitoring-plugins-basic

#install plugins dependencies only
apt install -y  `apt depends centreon-plugin* | sed 's/Depends: \(.*\)$/\1/g' | grep -v \< | sed 's/^ \+\(.*\)$/\1/g' | sort -u | grep -v centreon`

#uncomment to create engine without mapping /var/lib/centreon-engine, /var/log/centreon-engine  and /var/log/centreon-broker
#mkdir -p /var/log/centreon-engine /var/lib/centreon-engine/rw /var/log/centreon-broker
#chown -R centreon-engine: /var/log/centreon-engine /var/lib/centreon-engine /var/log/centreon-broker

EOF

