ARG REGISTRY_URL

FROM ${REGISTRY_URL}/almalinux:10

RUN --mount=type=bind,src=.,dst=/tmp/collect bash -e <<EOF

# Base dnf configuration
sed -i 's/best=True/best=False/g' /etc/dnf/dnf.conf
echo 'install_weak_deps=False' >> /etc/dnf/dnf.conf

dnf install -y dnf-plugins-core
dnf config-manager --set-enabled crb
dnf install -y epel-release

#    dsniff (tcpkill) unavailable on rhel10 at this time and not used by cma robot tests

dnf install --best -y \
    gcc \
    gcc-c++ \
    gdb \
    git \
    iptables \
    lua \
    mariadb-server \
    mariadb \
    openssh-server \
    openssl \
    python3 \
    python3-devel \
    python3-pip \
    perl-interpreter \
    procps-ng \
    psmisc \
    perl-HTTP-Daemon-SSL \
    perl-JSON \
    python3-setuptools \
    rrdtool \
    tcpdump \
    sudo \
    zstd

echo "install robot and dependencies"
pip3 install -U setuptools wheel
pip3 install -U robotframework robotframework-databaselibrary robotframework-httpctrl robotframework-examples pymysql python-dateutil psutil
pip3 install grpcio grpcio_tools py-cpuinfo cython gitpython boto3 robotframework-requests PyJWT

cd /tmp/collect

.github/scripts/collect-prepare-test-robot.sh mariadb

dnf remove -y gcc gcc-c++ python3-devel

dnf clean all

EOF
