ARG REGISTRY_URL

FROM ${REGISTRY_URL}/debian:bookworm

RUN --mount=type=bind,src=.,dst=/tmp/collect bash -e <<EOF

apt-get update

apt-get -y install \
    curl \
    g++ \
    gcc \
    gdb \
    git \
    libhttp-daemon-ssl-perl \
    libjson-perl \
    liblua5.3 \
    libmariadb3 \
    locales \
    mariadb-server \
    openssh-server \
    perl-base \
    psmisc \
    python3 \
    python3-dev \
    python3-pip \
    rrdcached \
    rrdtool \
    strace \
    sudo \
    zstd

apt-get clean

localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

pip3 install --break-system-packages -U robotframework robotframework-databaselibrary==2.0.4 robotframework-httpctrl robotframework-examples pymysql python-dateutil psutil
pip3 install --break-system-packages grpcio grpcio_tools py-cpuinfo cython unqlite gitpython boto3 robotframework-requests PyJWT

cd /tmp/collect

.github/scripts/collect-prepare-test-robot.sh mariadb

apt-get remove -y gcc g++ python3-dev
apt-get autoremove -y

apt-get clean

EOF

