ARG REGISTRY_URL

FROM ${REGISTRY_URL}/almalinux:9

COPY . /tmp/collect

RUN --mount=type=bind,src=.,dst=/tmp/collect bash -e <<EOF

# Base dnf configuration
sed -i 's/best=True/best=False/g' /etc/dnf/dnf.conf
echo 'install_weak_deps=False' >> /etc/dnf/dnf.conf

dnf install -y dnf-plugins-core
dnf config-manager --set-enabled crb
dnf install -y epel-release

# dnf install --best -y \
#     gcc \
#     gcc-c++ \
#     gdb \
#     git \
#     openssh-server \
#     mariadb-server \
#     mariadb \
#     gnutls \
#     libgcrypt \
#     lua \
#     perl-ExtUtils-Embed \
#     perl-JSON \
#     python3 \
#     python3-devel \
#     python3-pip \
#     perl-Thread-Queue \
#     rrdtool \
#     perl-interpreter \
#     procps-ng \
#     zstd \
#     psmisc \
#     perl-HTTP-Daemon-SSL.noarch \
#     sudo

dnf install --best -y \
    openssh-server \
    mariadb-server \
    mariadb \
    lua \
    python3 \
    python3-devel \
    python3-pip \
    rrdtool \
    perl-interpreter \
    procps-ng \
    zstd \
    psmisc \
    perl-HTTP-Daemon-SSL \
    perl-JSON \
    sudo

dnf clean all

echo "install robot and dependencies"

pip3 install -U robotframework robotframework-databaselibrary robotframework-httpctrl robotframework-examples pymysql python-dateutil psutil
pip3 install grpcio grpcio_tools py-cpuinfo cython unqlite gitpython boto3 robotframework-requests

cd /tmp/collect

.github/scripts/collect-prepare-test-robot.sh mariadb

dnf remove -y gcc gcc-c++ gdb python3-devel

dnf clean all

EOF
