ARG REGISTRY_URL

FROM ${REGISTRY_URL}/debian:bookworm

RUN <<EOF

apt-get update

echo 'http://deb.debian.org/debian' | apt-get install -y pbuilder

echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | tee /etc/apt/sources.list.d/goreleaser.list
apt-get update
apt-get install -y nfpm

apt-get clean

localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py
pip3 install --break-system-packages conan==1.61.0
ln -s /usr/local/bin/conan /usr/bin/conan
rm -rf ~/.conan/profiles/default

EOF

COPY conanfile.txt .

RUN <<EOF

cat conanfile.txt
conan install . -s compiler.cppstd=17 -s compiler.libcxx=libstdc++11 --build='missing'

EOF

WORKDIR /src
