this["Automation"] = this["Automation"] || {};
this["Automation"]["Templates"] = this["Automation"]["Templates"] || {};
this["Automation"]["Templates"]["homeNetwork"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  return "<div>\n\n    <div class=\"title\">\n        <h4>Discover local network</h4>\n    </div>\n    <div class=\"content discovery-content\">\n    </div>\n</div>";
  },"useData":true});
this["Automation"]["Templates"]["inputRange"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var helper, functionType="function", helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression;
  return "<div>\n\n    <label for=\"ip\">Enter your private IP Address</label>\n    <input id=\"inputRange\" type=\"text\" name=\"ip\" />\n    <span class=\"check-icon\">"
    + escapeExpression(((helper = (helper = helpers.icon || (depth0 != null ? depth0.icon : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"icon","hash":{},"data":data}) : helper)))
    + "</span>\n\n    <button id=\"sendRange\" type=\"button\" class=\"bt-circle\">\n        <span class=\"arrow\"></span>\n    </button>\n    <p class=\"note note-warning\">\n        <img src=\"./modules/centreon-automation/frontend/app/img/icons/warning.svg\" alt=\"warning\" /> We advise you to avoid <strong>Public IP addresses</strong>\n    </p>\n    <span class=\"error-msg\"></span>\n</div>";
},"useData":true});
this["Automation"]["Templates"]["scanNetwork"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  return "<div>\n    <table class=\"listing\">\n        <tr class=\"sticky-head\">\n            <th></th>\n            <th>IP address</th>\n            <th>Description</th>\n            <th>Active services</th>\n        </tr>\n    </table>\n    <div class=\"listing-container\">\n        <div class=\"error-container\"></div>\n        <div class=\"waiting floating-wait\">\n            <div class=\"loading-container\">\n                <svg id=\"icon-logo-centreon\" width=\"42\" height=\"42\" viewBox=\"0 0 46 46\" x=\"0\" y=\"0\">\n\n                    <path class= \"color color-1\" d=\"M41.3 5.6c-3.64-3.080-8.26-4.62-12.74-4.62v11.060c1.68 0 3.36 0.42 4.9 1.4v0c0.84 0.56 1.96 0.7 2.8-0.14l4.9-4.9c0.98-0.98 1.12-1.96 0.14-2.8z\"></path>\n                    <path class= \"color color-2\" d=\"M22.26 14.7c1.68-1.68 4.060-2.66 6.3-2.66v-11.060c-5.18 0-10.22 1.96-14.14 5.88l7.84 7.84z\"></path>\n                    <path class= \"color color-3\" d=\"M22.26 14.7l-7.84-7.84-13.72 12.46c-0.42 0.42-0.7 0.98-0.7 1.68h19.6c0.14-2.24 0.98-4.62 2.66-6.3z\"></path>\n                    <path class= \"color color-4\" d=\"M14.42 35.14l7.84-7.84c-1.68-1.68-2.66-4.060-2.66-6.3h-19.6c0 0.7 0.28 1.26 0.7 1.68l13.72 12.46c0 0 0 0 0 0v0 0 0z\"></path>\n                    <path class= \"color color-5\" d=\"M22.26 27.3v0l-7.84 7.84c3.92 3.92 8.96 5.88 14.14 5.88v-11.060c-2.24 0-4.48-0.84-6.3-2.66z\"></path>\n                    <path class= \"color color-6\" d=\"M41.16 33.6l-5.040-5.040c-0.84-0.84-1.96-0.7-2.8-0.14v0c-1.4 0.98-3.22 1.4-4.9 1.4v11.060c4.48 0 9.1-1.54 12.74-4.62 1.12-0.7 0.98-1.68 0-2.66z\"></path>\n\n                </svg>\n            </div>\n        </div>\n\n        <table class=\"listing scan-listing\"></table>\n\n    </div>\n    <div class=\"action-container hide\">\n        <input id=\"SearchA\" name=\"SearchA\" value=\"Use items and Add PING\" class=\"btc bt_success\" type=\"button\" />\n        <input id=\"SearchB\" name=\"SearchB\" value=\"Qualify items with SNMP\" class=\"btc bt_success\" type=\"button\" />\n    </div>\n</div>";
  },"useData":true});
this["Automation"]["Templates"]["steps"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var helper, functionType="function", helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression;
  return "<div>\n    <div class=\"title\">\n        <h4>Centreon Automation</h4>\n        <p class=\"step\"><strong>"
    + escapeExpression(((helper = (helper = helpers.step || (depth0 != null ? depth0.step : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"step","hash":{},"data":data}) : helper)))
    + "</strong></p>\n    </div>\n\n    <ul id=\"steps\">\n        <li id=\"step_1\" class=\"current-step\">\n            <h5>Put your private adress IP</h5>\n            <p class=\"stepHelp\">Help text for Automation module sed do\n                tempor incididunt ut labore et dolore magna aliqua.\n                Ut enim ad minim veniam, quis nostrud exercitation\n            </p>\n            <div class=\"range-view\"></div>\n        </li>\n        <li id=\"step_2\" class=\"next-step\">\n            <h5>Select Discovered items for Qualification</h5>\n            <p class=\"stepHelp\">Help text for Automation module sed do\n                tempor incididunt ut labore et dolore magna aliqua.\n                Ut enim ad minim veniam, quis nostrud exercitation\n            </p>\n        </li>\n        <li id=\"step_3\" class=\"next-step\">\n            <h5>Qualify Discovered items</h5>\n            <p class=\"stepHelp\">Help text for Automation module sed do\n                tempor incididunt ut labore et dolore magna aliqua.\n                Ut enim ad minim veniam, quis nostrud exercitation\n            </p>\n        </li>\n        <li id=\"step_4\" class=\"next-step\">\n            <h5>Select equipements and Configurate</h5>\n            <p class=\"stepHelp\">Help text for Automation module sed do\n                tempor incididunt ut labore et dolore magna aliqua.\n                Ut enim ad minim veniam, quis nostrud exercitation\n            </p>\n        </li>\n    </ul>\n</div>";
},"useData":true});
this["Automation"]["Templates"]["homePage"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  return "<div>\n\n    <div class=\"title\">\n        <h4>Welcome to centreon automation</h4>\n    </div>\n    <div class=\"content homepage-content\">\n        <p>\n            This menu allows to quickly start configuration of the first elements\n            in your monitoring platform through <b>Centreon Discovery</b> process.\n        </p>\n        <div class=\"bt-group\">\n            <button class=\"btc bt_success\" id=\"DiscoveryAction\">Start Discovery</button>\n            <button class=\"btc bt_success\" id=\"AddHostAction\">Add new host</button>\n        </div>\n    </div>\n\n</div>";
  },"useData":true});
this["Automation"]["Templates"]["introSide"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  return "<div>\n    <div class=\"title\">\n        <p class=\"step step-default\"><img src=\"./modules/centreon-automation/frontend/app/img/icons/logo.png\" alt=\"logo\" /></p>\n    </div>\n\n    <h4 class=\"intro-title\">Centreon Automation</h4>\n</div>";
  },"useData":true});