pipeline {
  agent { label 'C++' }
    stages {
      stage('Release Collect') {
        parameters([
          string(name: 'VERSION', defaultValue: '', description: 'Version to be released'),
          string(name: 'RELEASE', defaultValue: '', description: 'Release number')
        ])
        steps {
          echo 'Releasing Centreon Collect'
          sh './ci/scripts/release/collect-release.sh'
        }
      }
    }
}