ARG REGISTRY_URL=docker.centreon.com/centreon
ARG FROM_IMAGE_VERSION=develop

FROM ${REGISTRY_URL}/gorgone-testing-dependencies-trixie:${FROM_IMAGE_VERSION}

COPY centreon/centreon/www/install /usr/local/src/centreon/centreon/www/install

RUN --mount=type=bind,src=packages-centreon-gorgone,dst=/tmp/packages-centreon-gorgone \
    bash -e <<EOF

apt-get update

apt-get install -y /tmp/packages-centreon-gorgone/*.deb

apt-get clean
rm -rf /var/lib/apt/lists/*

EOF
