syntax = "proto3";


package com.centreon.connector.perl;

message GlobalError {
    string error = 1;
}


message Execute {
    uint64 cmd_id = 1;
    repeated string args = 2; // command arguments without script path
    bool no_child_create = 3; //if true and all child_script are running, we does not create a new child_script
    int64 timeout = 4;
}


message CheckChildStatistics {
    uint64 used_memory = 1;
    uint32 nb_opened_fd = 2;
    uint32 nb_threads = 3;
}

message Result {
    uint64 cmd_id = 1;
    int32 status = 2;
    string stdout = 3;
    CheckChildStatistics AfterFirstCheck = 4;
    CheckChildStatistics AfterLastCheck = 5;
}


message Terminate {
    uint64 pid = 1;
    bool immediate = 2;
}

message ConnectorMess {
    oneof content {
        GlobalError have_to_terminate = 1;
        Execute execute = 2;
        Result result = 3;
        Terminate terminate = 4;
    }
}