syntax = "proto3";


package com.centreon.connector.perl;


message Terminate {}

message Execute {
    uint64 check_id = 1;
    string exe = 2;
    repeated string args = 3;
}


message CheckChildStatistics {
    uint64 used_memory = 1;
    uint32 opened_fd = 2;
    uint32 nb_threads = 3;
}

message Result {
    uint64 check_id = 1;
    int32 status = 2;
    string stdout = 3;
    string stderr = 4;
    CheckChildStatistics AfterFirstCheck = 5;
    CheckChildStatistics AfterLastCheck = 6;
}


message ScriptChildStats {
    uint32 nb_child = 1;
    CheckChildStatistics max_check_child_load = 2;
}

message ScriptError {
    string embedded_file_write_error = 1;
    string embedded_file_compilation_error = 2;
    string check_script_error = 3;
}

message ConnectorMess {
    oneof content {
        Terminate terminate = 1;
        Execute execute = 2;
        Result result = 3;
        ScriptChildStats script_child_stat = 4;
    }
}