COPY dependencies/18.9/ioncube_loader_lin_7.1.so /opt/rh/rh-php71/root/usr/lib64/php/modules/ioncube_loader_lin_7.1.so
RUN chmod +x /opt/rh/rh-php71/root/usr/lib64/php/modules/ioncube_loader_lin_7.1.so
ENV PATH=$PATH:/opt/rh/rh-php71/root/usr/bin
