FROM almalinux:8

ARG VERSION=24.10

RUN bash -e <<EOF

echo 'install_weak_deps=False' >> /etc/dnf/dnf.conf
echo 'max_parallel_downloads=10' >> /etc/dnf/dnf.conf
echo 'fastestmirror=True' >> /etc/dnf/dnf.conf

dnf install -y dnf-plugins-core zstd curl mariadb iproute epel-release procps lsof
dnf config-manager --set-enabled 'powertools'
dnf -y config-manager --add-repo https://packages.centreon.com/rpm-standard/${VERSION}/el8/centreon-${VERSION}.repo
dnf -y clean all --enablerepo=*
dnf install -y python3.11 python3.11-pip
pip3.11 install robotframework robotframework-examples robotframework-databaselibrary pymysql robotframework-requests robotframework-jsonlibrary
pip3.11 cache purge

# Install nodejs
curl -fsSL https://rpm.nodesource.com/setup_24.x | bash -
dnf install -y nodejs
# Install mockoon (needs nodejs)
npm install -g -D @mockoon/cli@9.3.0
npm cache clean --force

dnf install -y \
  "perl-Libssh-Session" \
  "perl-Mojolicious" \
  "perl(lib)" \
  "perl(Clone)" \
  "perl(DateTime)" \
  "perl(DBD::mysql)" \
  "perl(EV)" \
  "perl(HTTP::Daemon::SSL)" \
  "perl(Net::Curl::Easy)" \
  "perl(JSON)" \
  "perl(RRDs)" \
  "perl(XML::Simple)" \
  "perl(ZMQ::FFI)"

dnf clean all

EOF
