name: "parse-distrib"
description: "parse distrib name."
inputs:
  distrib:
    description: "The distribution name"
    required: true
outputs:
  package_distrib_separator:
    description: "Separator between package version and distrib number"
    value: ${{ steps.parse-distrib.outputs.package_distrib_separator }}
  package_version_separator:
    description: "Separator between package name and package version"
    value: ${{ steps.parse-distrib.outputs.package_version_separator }}
  package_distrib_name:
    description: "Distribution suffix in package name"
    value: ${{ steps.parse-distrib.outputs.package_distrib_name }}
  package_extension:
    description: "Package extension according to the distribution"
    value: ${{ steps.parse-distrib.outputs.package_extension }}
  distrib_family:
    description: "Distrib family (el, debian, ubuntu)"
    value: ${{ steps.parse-distrib.outputs.distrib_family }}
  distrib_name:
    description: "Distribution name"
    value: ${{ steps.parse-distrib.outputs.distrib_name }}
  repo_distrib_name:
    description: "Distribution name for repository paths"
    value: ${{ steps.parse-distrib.outputs.repo_distrib_name }}

runs:
  using: "composite"
  steps:
    - name: Parse distrib
      id: parse-distrib
      env:
        DISTRIB: ${{ inputs.distrib }}
      run: |
        if [[ "$DISTRIB" == "centos7" || "$DISTRIB" == "el7" ]]; then
          PACKAGE_DISTRIB_SEPARATOR="."
          PACKAGE_VERSION_SEPARATOR="-"
          PACKAGE_DISTRIB_NAME="el7"
          PACKAGE_EXTENSION="rpm"
          DISTRIB_FAMILY="el7"
          DISTRIB_NAME="centos7"
          REPO_DISTRIB_NAME="el7"
        elif [[ "$DISTRIB" == "alma8" || "$DISTRIB" == "el8" ]]; then
          PACKAGE_DISTRIB_SEPARATOR="."
          PACKAGE_VERSION_SEPARATOR="-"
          PACKAGE_DISTRIB_NAME="el8"
          PACKAGE_EXTENSION="rpm"
          DISTRIB_FAMILY="el8"
          DISTRIB_NAME="alma8"
          REPO_DISTRIB_NAME="el8"
        elif [[ "$DISTRIB" == "alma9" || "$DISTRIB" == "el9" ]]; then
          PACKAGE_DISTRIB_SEPARATOR="."
          PACKAGE_VERSION_SEPARATOR="-"
          PACKAGE_DISTRIB_NAME="el9"
          PACKAGE_EXTENSION="rpm"
          DISTRIB_FAMILY="el9"
          DISTRIB_NAME="alma9"
          REPO_DISTRIB_NAME="el9"
        elif [[ "$DISTRIB" == "alma10" || "$DISTRIB" == "el10" ]]; then
          PACKAGE_DISTRIB_SEPARATOR="."
          PACKAGE_VERSION_SEPARATOR="-"
          PACKAGE_DISTRIB_NAME="el10"
          PACKAGE_EXTENSION="rpm"
          DISTRIB_FAMILY="el10"
          DISTRIB_NAME="alma10"
          REPO_DISTRIB_NAME="el10"
        elif [[ "$DISTRIB" == "bullseye" ]]; then
          PACKAGE_DISTRIB_SEPARATOR="+"
          PACKAGE_VERSION_SEPARATOR="_"
          PACKAGE_DISTRIB_NAME="deb11u1"
          PACKAGE_EXTENSION="deb"
          DISTRIB_FAMILY="debian"
          DISTRIB_NAME="bullseye"
          REPO_DISTRIB_NAME="bullseye"
        elif [[ "$DISTRIB" == "bookworm" ]]; then
          PACKAGE_DISTRIB_SEPARATOR="+"
          PACKAGE_VERSION_SEPARATOR="_"
          PACKAGE_DISTRIB_NAME="deb12u1"
          PACKAGE_EXTENSION="deb"
          DISTRIB_FAMILY="debian"
          DISTRIB_NAME="bookworm"
          REPO_DISTRIB_NAME="bookworm"
        elif [[ "$DISTRIB" == "trixie" ]]; then
          PACKAGE_DISTRIB_SEPARATOR="+"
          PACKAGE_VERSION_SEPARATOR="_"
          PACKAGE_DISTRIB_NAME="deb13u1"
          PACKAGE_EXTENSION="deb"
          DISTRIB_FAMILY="debian"
          DISTRIB_NAME="trixie"
          REPO_DISTRIB_NAME="trixie"
        elif [[ "$DISTRIB" == "jammy" ]]; then
          PACKAGE_DISTRIB_SEPARATOR="-"
          PACKAGE_VERSION_SEPARATOR="_"
          PACKAGE_DISTRIB_NAME="0ubuntu.22.04"
          PACKAGE_EXTENSION="deb"
          DISTRIB_FAMILY="ubuntu"
          DISTRIB_NAME="jammy"
          REPO_DISTRIB_NAME="jammy"
        elif [[ "$DISTRIB" == "noble" ]]; then
          PACKAGE_DISTRIB_SEPARATOR="-"
          PACKAGE_VERSION_SEPARATOR="_"
          PACKAGE_DISTRIB_NAME="0ubuntu.24.04"
          PACKAGE_EXTENSION="deb"
          DISTRIB_FAMILY="ubuntu"
          DISTRIB_NAME="noble"
          REPO_DISTRIB_NAME="noble"
        elif [[ "$DISTRIB" == "alpine" ]]; then
          PACKAGE_DISTRIB_SEPARATOR="-"
          PACKAGE_VERSION_SEPARATOR="-"
          PACKAGE_DISTRIB_NAME="alpine3.20"
          PACKAGE_EXTENSION="apk"
          DISTRIB_FAMILY="alpine"
          DISTRIB_NAME="alpine"
          REPO_DISTRIB_NAME="alpine"
        else
          echo "::error::Distrib $DISTRIB cannot be parsed"
          exit 1
        fi
        echo "package_distrib_separator=$PACKAGE_DISTRIB_SEPARATOR" >> $GITHUB_OUTPUT
        echo "package_version_separator=$PACKAGE_VERSION_SEPARATOR" >> $GITHUB_OUTPUT
        echo "package_distrib_name=$PACKAGE_DISTRIB_NAME" >> $GITHUB_OUTPUT
        echo "package_extension=$PACKAGE_EXTENSION" >> $GITHUB_OUTPUT
        echo "distrib_family=$DISTRIB_FAMILY" >> $GITHUB_OUTPUT
        echo "distrib_name=$DISTRIB_NAME" >> $GITHUB_OUTPUT
        echo "repo_distrib_name=$REPO_DISTRIB_NAME" >> $GITHUB_OUTPUT
      shell: bash
