# Base information.
FROM @BASE_IMAGE@
LABEL maintainer="Kevin Duret <kduret@centreon.com>"

# Install repository.
COPY centreon-react-components /tmp/centreon-react-components
WORKDIR /tmp/centreon-react-components

RUN npm ci

ENTRYPOINT ["npm", "run", "storybook"]