/*
** Pipeline code.
*/

stage('Dependencies containers creation') {
  parallel 'centos7 dependencies': {
    node {
      dir('centreon-collect-centos7') {
        checkout scm
        dir ('ci/docker') {
          sh 'cp ../../conanfile.txt .'
          sh 'docker build --no-cache . -f Dockerfile.collect-centos7-dependencies -t registry.centreon.com/centreon-collect-centos7-dependencies:22.10'
          sh 'docker push registry.centreon.com/centreon-collect-centos7-dependencies:22.10'
        }
      }
    }
  },
  'debian 10 dependencies': {
    node {
      dir('centreon-collect-debian10') {
        checkout scm
        dir ('ci/docker') {
          sh 'cp ../../conanfile.txt .'
          sh 'docker build --no-cache . -f Dockerfile.collect-debian10-dependencies -t registry.centreon.com/centreon-collect-debian10-dependencies:22.10'
          sh 'docker push registry.centreon.com/centreon-collect-debian10-dependencies:22.10'
        }
      }
    }
  },
  'debian 11 dependencies': {
    node {
      dir('centreon-collect-debian11') {
        checkout scm
        dir ('ci/docker') {
          sh 'cp ../../conanfile.txt .'
          sh 'docker build --no-cache . -f Dockerfile.collect-debian11-dependencies -t registry.centreon.com/centreon-collect-debian11-dependencies:22.10'
          sh 'docker push registry.centreon.com/centreon-collect-debian11-dependencies:22.10'
        }
      }
    }
  },
  'centos8 dependencies': {
    node {
      dir('centreon-collect-alma8') {
        checkout scm
        dir ('ci/docker') {
          sh 'cp ../../conanfile.txt .'
          sh 'docker build --no-cache . -f Dockerfile.collect-alma8-dependencies -t registry.centreon.com/centreon-collect-alma8-dependencies:22.10'
          sh 'docker push registry.centreon.com/centreon-collect-alma8-dependencies:22.10'
        }
      }
    }
  }
}
