/*
** Pipeline code.
*/

stage('Dependencies containers creation') {
  parallel 'centos7 dependencies': {
    node {
      dir('centreon-collect-centos7') {
        checkout scm
        dir ('ci/docker') {
          sh 'docker build --no-cache . -f Dockerfile.collect-centos7-dependencies -t registry.centreon.com/centreon-collect-centos7-dependencies:22.04'
          sh 'docker push registry.centreon.com/centreon-collect-centos7-dependencies:22.04'
        }
      }
    }
  },
  'debian 10 dependencies': {
    node {
      dir('centreon-collect-debian10') {
        checkout scm
        dir ('ci/docker') {
          sh 'docker build --no-cache . -f Dockerfile.collect-debian10-dependencies -t registry.centreon.com/centreon-collect-debian10-dependencies:22.04'
          sh 'docker push registry.centreon.com/centreon-collect-debian10-dependencies:22.04'
        }
      }
    }
  },
  'debian 11 ependencies': {
    node {
      dir('centreon-collect-debian11') {
        checkout scm
        dir ('ci/docker') {
          sh 'docker build --no-cache . -f Dockerfile.collect-debian11-dependencies -t registry.centreon.com/centreon-collect-debian11-dependencies:22.04'
          sh 'docker push registry.centreon.com/centreon-collect-debian11-dependencies:22.04'
        }
      }
    }
  },
  'centos8 dependencies': {
    node {
      dir('centreon-collect-centos8') {
        checkout scm
        dir ('ci/docker') {
          sh 'docker build --no-cache . -f Dockerfile.collect-centos8-dependencies -t registry.centreon.com/centreon-collect-centos8-dependencies:22.04'
          sh 'docker push registry.centreon.com/centreon-collect-centos8-dependencies:22.04'
        }
      }
    }
  }
}
