#!/bin/sh

if [ "$1" = "configure" ] ; then
    adduser --system --group --no-create-home centreon-engine
    usermod -a -G centreon-engine centreon
    chown -R centreon-engine:centreon-engine \
        /etc/centreon-engine \
        /var/lib/centreon-engine \
        /var/log/centreon-engine

    mv /usr/share/centreon-engine/extra/centreon-engine_integrate_centreon_engine2centreon.sh /usr/share/centreon-engine/extra/integrate_centreon_engine2centreon.sh
    chmod 0755 /usr/share/centreon-engine/extra/integrate_centreon_engine2centreon.sh
    chown root:root /usr/share/centreon-engine/extra/integrate_centreon_engine2centreon.sh
fi
