@Library('centreon-shared-library') _

pipeline {

    agent none
    triggers {
        cron('0 0 * * *')
    }
    stages {
      stage('Launch Centreon Tests') {
        stage('Robot Tests Execution') {
          agent any
          when { branch 'master'; branch 'develop'; branch 'COPS-824-cicd-create-pipeline-centreon-test-on-centreon-collect'
                 beforeAgent true }
          steps {
            sh 'docker run -i --entrypoint /src/ci/scripts/ENTRYPOINTSCRIPT -v "$PWD:/src" DOCKERIMAGE'
            robot outputPath: 'centreon-tests', logFileName: 'log.html', outputFileName: 'output.xml', reportFileName: 'report.hml', passThreshold: 100, unstableThreshold: 75.0
          }
          post { always { cleanWs() }}
        }
      }
    }
}
