@Library('centreon-shared-library') _

pipeline {

    agent none
    triggers {
        cron('0 0 * * *')
    }
    stages {
      stage('Launch Centreon Tests') {
          agent any
          // when { anyOf { branch 'dev-21.10.x'; branch '21.10.x' } }
          steps {
            sh 'docker run -i --entrypoint /src/ci/scripts/collect-test-robot.sh -v "$PWD:/src" registry.centreon.com/centreon-collect-centos7-dependencies:21.10'
            robot outputPath: 'centreon-tests', logFileName: 'log.html', outputFileName: 'output.xml', reportFileName: 'report.html', passThreshold: 100, unstableThreshold: 75.0
          }
          post { always { cleanWs() }}
      }
    }
}
