/**
 * Copyright 2026 Centreon
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * For more information : contact@centreon.com
 */

#include "com/centreon/broker/otlp/connector.hh"

#include "com/centreon/broker/neb/internal.hh"
#include "com/centreon/broker/otlp/otlp_exporter.hh"
#include "com/centreon/broker/otlp/resource_enricher.hh"
#include "com/centreon/broker/otlp/stream.hh"
#include "com/centreon/common/pool.hh"
#include "common/log_v2/log_v2.hh"

using namespace com::centreon::broker;
using namespace com::centreon::broker::otlp;
using log_v2 = com::centreon::common::log_v2::log_v2;

/* Status events rather than storage::pb_metric: the metric events are
 * generated by unified_sql, so a module built on them could not work at all in
 * a pipeline without unified_sql and a database. */
static constexpr multiplexing::muxer_filter _otlp_stream_filter = {
    neb::pb_service_status::static_type(), neb::pb_host_status::static_type(),
    /* resource attributes of hosts monitored by a Centreon Monitoring Agent */
    neb::pb_agent_host_info::static_type()};

/* Reversing the mandatory filter makes the applier force exactly this set and
 * ignore any user "filters" block*/
static constexpr multiplexing::muxer_filter _otlp_forbidden_filter =
    multiplexing::muxer_filter(_otlp_stream_filter).reverse();

/**
 * @brief Construct the endpoint and load its metric mapping.
 *
 * @throw msg_fmt if a mapping file is configured but can't be loaded.
 */
connector::connector(const otlp_config::pointer& conf)
    : io::endpoint(false, _otlp_stream_filter, _otlp_forbidden_filter),
      _conf(conf),
      _host_metadata(std::make_shared<host_metadata_store>(
          std::chrono::seconds(conf->host_metadata_ttl))) {
  auto logger = log_v2::instance().get(log_v2::OTL);
  _mapping = _conf->mapping_file.empty()
                 ? mapping_provider::empty(logger)
                 : mapping_provider::load(
                       com::centreon::common::pool::io_context_ptr(),
                       _conf->mapping_file, logger);
}

std::shared_ptr<io::stream> connector::open() {
  auto logger = log_v2::instance().get(log_v2::OTL);
  return std::make_shared<stream>(
      _conf, std::make_shared<global_cache_enricher>(), _mapping,
      std::make_shared<otlp_exporter>(_conf, logger), logger, _host_metadata);
}
