# Base information.
FROM ci.int.centreon.com:5000/mon-web:@DISTRIB@
MAINTAINER Matthieu Kermagoret <mkermagoret@centreon.com>

# Install package.
RUN yum --disablerepo='*' --enablerepo=ces-standard-unstable-noarch clean all
RUN yum install -y --nogpgcheck centreon-bam-server

# Install module in Centreon.
COPY install-centreon-module.php /tmp/install-centreon-module.php
COPY bam/install.sh /tmp/install.sh
RUN chmod +x /tmp/install-centreon-module.php /tmp/install.sh
RUN /tmp/install.sh
