include(FindPkgConfig)
# Find MySQL/Mariadb devel package
pkg_check_modules(_libmariadb libmariadb)
if (_libmariadb_FOUND)
  set(MYSQL_CFLAGS ${_libmariadb_CFLAGS})
  set(MYSQL_LIBS ${_libmariadb_LDFLAGS})
else ()
  pkg_check_modules(_mariadb mariadb)
  if (_mariadb_FOUND)
    set(MYSQL_CFLAGS ${_mariadb_CFLAGS})
    set(MYSQL_LIBS ${_mariadb_LDFLAGS})
  else ()
    pkg_check_modules(_mysql mysql)
    if (_mysql_FOUND)
      set(MYSQL_CFLAGS ${_mysql_CFLAGS})
      set(MYSQL_LIBS ${_mysql_LDFLAGS})
    else ()
      message(SEND_ERROR "MariaDB devel package is not installed")
    endif ()
  endif ()
endif ()

string(REPLACE "-" " -" MYSQL_CFLAGS ${MYSQL_CFLAGS})
message(STATUS ${MYSQL_CFLAGS})
message(STATUS ${MYSQL_LIBS})