name: gorgoned-poller
gorgonecore:
  internal_com_type: ipc
  internal_com_path: /tmp/gorgone/routing-poller.ipc
  # in seconds before sending kill signals (not gently)
  timeout: 50
  gorgone_db_type: SQLite
  gorgone_db_name: dbname=/tmp/gorgone_poller.sdb
  gorgone_db_host: 
  gorgone_db_port: 
  gorgone_db_user:
  gorgone_db_password:
  # If not set. Use 'hostname' function.
  hostname:
  # If not set. Try from 'hostname' in database
  # Set 'none', if you don't need it (for poller in push mode)
  id: 120
  privkey: keys/privkey.pem
  cipher: "Crypt::OpenSSL::AES"
  # in bytes
  keysize: 32
  # 16 bytes for AES
  vector: 0123456789012345
  # in seconds
  sessions_time: 86400
  # in seconds
  purge_sessions_time: 3600
modules:
  - name: gorgonepull
    module: modules::gorgonepull::hooks
    enable: true
    target_type: tcp
    target_path: 127.0.0.1:5555
    linger: 5000

    # crypt options
    server_pubkey: keys/central/pubkey.crt
    client_pubkey: keys/poller/pubkey.crt
    client_privkey: keys/poller/privkey.pem
    
    cipher: "Cipher::AES"
    # in bytes
    keysize: 32
    # 16 bytes for AES
    vector: 0123456789012345

    # ping
    ping: 60
    ping_timeout: 30
  - name: gorgoneaction
    module: modules::gorgoneaction::hooks
    enable: true
    disable_command_event: 0
    disable_enginecomand_event: 0
    enginecommand_timeout: 30
    command_timeout: 60
    # characters to delete in commands
    paranoid_mode: 1
    paranoid_characters:
