name: gorgoned-poller
description: Configuration example in a full ZMQ environment for Poller server
gorgonecore:
  internal_com_type: ipc
  internal_com_path: /tmp/gorgone/routing-poller.ipc
  external_com_type: tcp
  external_com_path: "*:5556"
  # in seconds before sending kill signals (not gently)
  timeout: 50
  gorgone_db_type: SQLite
  gorgone_db_name: dbname=/tmp/gorgone.sdb
  id: 2
  privkey: keys/poller/privkey.pem
  cipher: "Cipher::AES"
  # in bytes
  keysize: 32
  # 16 bytes for AES
  vector: 0123456789012345
  # JWK format export thumbprint SHA256
  authorized_clients: 
    - key: pnI6EWkiTbazjikJXRkLmjml5wvVECYtQduJUjS4QK4
  # in seconds
  sessions_time: 86400
  # in seconds
  purge_sessions_time: 3600
modules:
  - name: action
    package: modules::core::action::hooks
    enable: true

  - name: engine
    package: modules::centreon::engine::hooks
    enable: true
    command_file: "/var/lib/centreon-engine/rw/centengine.cmd"
