name: gorgoned-poller2
gorgonecore:
  internal_com_type: ipc
  internal_com_path: /tmp/gorgone/routing-poller2.ipc
  external_com_type: tcp
  external_com_path: "*:5557"
  # in seconds before sending kill signals (not gently)
  timeout: 50
  gorgone_db_type: SQLite
  gorgone_db_name: dbname=/tmp/gorgone_poller2.sdb
  gorgone_db_host: 
  gorgone_db_port: 
  gorgone_db_user:
  gorgone_db_password:
  # If not set. Use 'hostname' function.
  hostname:
  # If not set. Try from 'hostname' in database
  # Set 'none', if you don't need it (for poller in push mode)
  id: 150
  privkey: keys/poller/privkey.pem
  cipher: "Cipher::AES"
  # in bytes
  keysize: 32
  # 16 bytes for AES
  vector: 0123456789012345
  # JWK format export thumbprint SHA256
  authorized_clients: 
    - key: pnI6EWkiTbazjikJXRkLmjml5wvVECYtQduJUjS4QK4

  # in seconds
  sessions_time: 86400
  # in seconds
  purge_sessions_time: 3600
modules:
  - name: action
    package: modules::core::action::hooks
    enable: true
  
