name: gorgoned-central-ssh
description: Configuration example in a SSH environment for Central server
database:
  db_centreon: 
    dsn: "mysql:host=localhost;dbname=centreon"
    username: centreon
    password: centreon
  db_centstorage: 
    dsn: "mysql:host=localhost;dbname=centreon_storage"
    username: centreon
    password: centreon
gorgonecore:
  internal_com_type: ipc
  internal_com_path: /tmp/gorgone/routing.ipc
  external_com_type: tcp
  external_com_path: "*:5555"
  # in seconds before sending kill signals (not gently)
  timeout: 50
  gorgone_db_type: SQLite
  gorgone_db_name: dbname=/tmp/gorgone.sdb
  privkey: keys/central/privkey.pem
  cipher: "Cipher::AES"
  # in bytes
  keysize: 32
  # 16 bytes for AES
  vector: 0123456789012345
  # JWK format export thumbprint SHA256
  authorized_clients: 
    - key: pnI6EWkiTbazjikJXRkLmjml5wvVECYtQduJUjS4QK4
  # in seconds
  sessions_time: 86400
modules:
  - name: httpserver
    package: gorgone::modules::core::httpserver::hooks
    enable: true
    address: 0.0.0.0
    port: 8443
    ssl: true
    ssl_cert_file: /etc/pki/tls/certs/server-cert.pem
    ssl_key_file: /etc/pki/tls/server-key.pem
    auth:
      user: admin
      password: password

  - name: cron
    package: gorgone::modules::core::cron::hooks
    enable: true
    cron:
      - id: echo_date
        timespec: "*/5 * * * *"
        action: COMMAND
        parameters:
          command: "date >> /tmp/date.log"
          timeout: 10

  - name: action
    package: gorgone::modules::core::action::hooks
    enable: true

  - name: proxy
    package: gorgone::modules::core::proxy::hooks
    enable: true

  - name: pollers
    package: gorgone::modules::centreon::pollers::hooks
    enable: true

  - name: legacycmd
    package: gorgone::modules::centreon::legacycmd::hooks
    enable: true
    cmd_file: "/var/lib/centreon/centcore.cmd"
    cache_dir: "/var/cache/centreon/"
    cache_dir_trap: "/etc/snmp/centreon_traps/"
    remote_dir: "/var/lib/centreon/remote-data/"

  - name: engine
    package: gorgone::modules::centreon::engine::hooks
    enable: true
    command_file: "/var/lib/centreon-engine/rw/centengine.cmd"
