nodes:
  - id: 2
    type: push_zmq
    address: 10.30.2.90
    port: 5556
    server_pubkey: keys/poller/pubkey.crt
    client_pubkey: keys/central/pubkey.crt
    client_privkey: keys/central/privkey.pem
    cipher: "Cipher::AES" 
    keysize: 32
    vector: 0123456789012345
