# Base information.
FROM ci.int.centreon.com:5000/mon-web-18.9:@DISTRIB@
LABEL maintainer="Kevin Duret <kduret@centreon.com>"

# Install package.
RUN yum --enablerepo='centreon-internal*' clean all && \
    yum install -y centreon-auto-discovery-server && \
    yum clean all

# Install module in Centreon.
COPY web/18.9/install-centreon-module.php /tmp/install-centreon-module.php
COPY autodisco/18.9/install.sh /tmp/install.sh
RUN chmod +x /tmp/install-centreon-module.php /tmp/install.sh && \
    /tmp/install.sh
