name: broker-analysis

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * 1-5'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - ".version"
      - broker/**
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - ".version"
      - broker/**

jobs:
  get-environment:
    uses: ./.github/workflows/get-environment.yml
    with:
      version_file: CMakeLists.txt
      nightly_manual_trigger: ${{ inputs.nightly_manual_trigger || false }}

  checkmarx-analysis:
    needs: [get-environment]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.is_targeting_feature_branch != 'true' &&
      github.event.pull_request.draft != 'true'
    uses: ./.github/workflows/checkmarx-analysis.yml
    with:
      module_directory: broker
      module_name: centreon-broker
    secrets:
      base_uri: ${{ secrets.AST_RND_SCANS_BASE_URI }}
      cx_tenant: ${{ secrets.AST_RND_SCANS_TENANT }}
      cx_client_id: ${{ secrets.AST_RND_SCANS_CLIENT_ID }}
      cx_client_secret: ${{ secrets.AST_RND_SCANS_CLIENT_SECRET }}

#  set-skip-label:
#    needs: [get-environment, checkmarx-analysis]
#    if: needs.get-environment.outputs.skip_workflow == 'false'
#    uses: ./.github/workflows/set-pull-request-skip-label.yml
