name: broker-analysis
run-name: ${{ (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.nightly_manual_trigger == 'true')) && format('{0} nightly {1}', github.workflow, github.ref_name) || '' }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      nightly_manual_trigger:
        description: 'Set to true for nightly run'
        required: true
        default: false
        type: boolean
  schedule:
    - cron: '30 0 * * 1-5'
  pull_request:
    paths:
      - broker/**
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - broker/**

jobs:
  dependency-scan:
    uses: centreon/security-tools/.github/workflows/dependency-analysis.yml@main

  get-environment:
    needs: [dependency-scan]
    if: github.repository == 'centreon/centreon-collect'
    uses: ./.github/workflows/get-environment.yml
    with:
      version_file: CMakeLists.txt
      nightly_manual_trigger: ${{ inputs.nightly_manual_trigger || false }}

  dispatch-to-maintained-branches:
    needs: [get-environment]
    if: |
      github.run_attempt == 1 &&
      github.event_name == 'schedule' &&
      github.ref_name == 'develop' &&
      needs.get-environment.outputs.skip_workflow == 'false'

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - run: |
          NIGHTLY_TARGETS=("dev-23.10.x" "dev-24.04.x" "dev-24.10.x")
          for target in "${NIGHTLY_TARGETS[@]}"; do
            echo "[INFO] - Dispatching nightly run to $target branch."
            gh workflow run broker-analysis.yml -r "$target" -f nightly_manual_trigger=true
          done
        shell: bash
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code_scan:
    needs: [get-environment]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      github.event.pull_request.draft != 'true'
    uses: centreon/security-tools/.github/workflows/checkmarx-analysis.yml@main
    with:
      module_directory: broker
      module_name: centreon-broker-dev-${{ needs.get-environment.outputs.major_version }}.x
      exclude_list:
    secrets:
      base_uri: ${{ secrets.AST_RND_SCANS_BASE_URI }}
      cx_tenant: ${{ secrets.AST_RND_SCANS_TENANT }}
      cx_client_id: ${{ secrets.AST_RND_SCANS_CLIENT_ID }}
      cx_client_secret: ${{ secrets.AST_RND_SCANS_CLIENT_SECRET }}

  set-skip-label:
    needs: [get-environment, code_scan]
    if: needs.get-environment.outputs.skip_workflow == 'false'
    uses: ./.github/workflows/set-pull-request-skip-label.yml
