name: collect
run-name: |
  ${{
    (github.event_name == 'schedule' ||
     (github.event_name == 'workflow_dispatch' &&
      (github.event.inputs.nightly_manual_trigger == 'true' || github.event.inputs.robot_pattern != '^((?!cma).)*$')
     )
    )
    && format('collect nightly {0}', github.ref_name)
    || ''
  }}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      nightly_manual_trigger:
        description: "Set to true for nightly run"
        required: true
        default: false
        type: boolean
      robot_pattern:
        description: "filter robot files with regex"
        required: true
        default: "^((?!cma).)*$"
        type: string
      labels:
        description: "Labels to add to the run (comma separated)"
        required: false
        default: ""
        type: string

  schedule:
    - cron: "30 0 * * 1-5"
  pull_request:
    paths:
      - ".github/workflows/collect.yml"
      - ".version"
      - ".version.centreon-collect"
      - bbdo/**
      - broker/**
      - ccc/**
      - clib/**
      - connectors/**
      - custom-triplets/**
      - engine/**
      - grpc/**
      - packaging/centreon-collect/**
      - cmake.sh
      - cmake-vcpkg.sh
      - CMakeLists.txt
      - CMakeListsLinux.txt
      - vcpkg.json
      - overlays/**
      - selinux/centreon-broker/**
      - selinux/centreon-engine/**
      - tests/**
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
      - "release-[2-9][0-9].[0-9][0-9]-next"
      - "hotfix-[2-9][0-9].[0-9][0-9]-next"
    paths:
      - ".version"
      - ".version.centreon-collect"
      - bbdo/**
      - broker/**
      - ccc/**
      - clib/**
      - connectors/**
      - custom-triplets/**
      - engine/**
      - grpc/**
      - packaging/centreon-collect/**
      - cmake.sh
      - cmake-vcpkg.sh
      - CMakeLists.txt
      - CMakeListsLinux.txt
      - vcpkg.json
      - overlays/**
      - selinux/centreon-broker/**
      - selinux/centreon-engine/**
      - tests/**
    tags:
      - "centreon-collect-*"

jobs:
  dependency-scan:
    uses: centreon/security-tools/.github/workflows/dependency-analysis.yml@main

  dispatch-to-maintenance-branches:
    if: |
      github.run_attempt == 1 &&
      github.event_name == 'schedule' &&
      github.ref_name == 'develop' &&
      github.repository == 'centreon/centreon-collect'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Select maintenance branch and run nightly workflow on it
        uses: ./.github/actions/dispatch-to-maintenance-branch

  get-environment:
    needs: [dependency-scan]
    uses: ./.github/workflows/get-environment.yml
    with:
      version_file: CMakeLists.txt
      nightly_manual_trigger: ${{ inputs.nightly_manual_trigger || inputs.robot_pattern != '^((?!cma).)*$' || false }}
      labels: ${{ inputs.labels || '' }}

  get-aws-environment:
    uses: ./.github/workflows/get-aws-environment.yml

  check-version-consistency:
    runs-on: ubuntu-24.04
    needs: [get-environment]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability == 'testing'
    env:
      version: ${{ needs.get-environment.outputs.major_version }}.${{ needs.get-environment.outputs.minor_version }}
      version_file: .version.centreon-collect
      cmake_file: CMakeLists.txt
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check ${{ env.version_file }}
        uses: ./.github/actions/check-version-consistency
        with:
          file: ${{ env.version_file }}
          version: ${{ env.version }}

      - name: Check ${{ env.cmake_file }}
        uses: ./.github/actions/check-version-consistency
        with:
          file: ${{ env.cmake_file }}
          version: ${{ env.version }}

  changes:
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable'
    needs: [get-environment]
    uses: ./.github/workflows/get-changes-triggers.yml
    with:
      production_paths: |
        ".version"
        ".version.centreon-collect"
        "bbdo/**"
        "broker/**"
        "ccc/**"
        "clib/**"
        "connectors/**"
        "custom-triplets/**"
        "engine/**"
        "grpc/**"
        "packaging/centreon-collect/**"
        "cmake.sh"
        "cmake-vcpkg.sh"
        "CMakeLists.txt"
        "CMakeListsLinux.txt"
        "vcpkg.json"
        "overlays/**"
        "selinux/centreon-broker/**"
        "selinux/centreon-engine/**"
        "!**/test/**"
        "!**/tests/**"
        "!agent/test/**"
      unit_test_paths: |
        "**/test/**"
        "**/tests/**"
        "!tests/**"
        "!gorgone/tests/**"
      e2e_test_paths: |
        "resources/**"
        "tests/**"
        "!tests/**/cma.robot"
      is_nightly: ${{ needs.get-environment.outputs.is_nightly }}
      base_sha: ${{ needs.get-environment.outputs.previous_release_bundle_tag }}
      labels: ${{ needs.get-environment.outputs.labels }}

  package:
    needs:
      [get-environment, get-aws-environment, changes, check-version-consistency]
    if: |
      needs.changes.outputs.trigger_packaging == 'true' &&
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable' &&
      ! cancelled() &&
      ! contains(needs.*.result, 'failure') &&
      ! contains(needs.*.result, 'cancelled')
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.get-environment.outputs.collect_matrix) }}

    name: package ${{ matrix.operating_system }} ${{ matrix.arch }}

    uses: ./.github/workflows/package-collect.yml

    with:
      major_version: ${{ needs.get-environment.outputs.major_version }}
      minor_version: ${{ needs.get-environment.outputs.minor_version }}
      cma_major_version: ${{ needs.get-environment.outputs.cma_major_version }}
      cma_minor_version: ${{ needs.get-environment.outputs.cma_minor_version }}
      img_version: ${{ needs.get-environment.outputs.packaging_img_version }}
      release: ${{ needs.get-environment.outputs.release }}
      commit_hash: ${{ github.sha }}
      stability: ${{ needs.get-environment.outputs.stability }}
      legacy_engine: "OFF"
      build_debug_packages: ${{ needs.get-environment.outputs.stability == 'testing' || contains(github.event.pull_request.labels.*.name, 'build-debug-packages') }}
      packages_in_artifact: ${{ needs.get-environment.outputs.is_nightly == 'true' || contains(needs.get-environment.outputs.labels, 'upload-artifacts') }}
      image: ${{ format('packaging-centreon-collect-vcpkg-{0}{1}', matrix.operating_system, matrix.arch == 'arm64' && '-arm64' || '') }}
      distrib: ${{ matrix.operating_system }}
      arch: ${{ matrix.arch }}
      is_nightly: ${{ needs.get-environment.outputs.is_nightly }}
      only_robot_cma: false
      aws_role_arn: ${{ needs.get-aws-environment.outputs.aws_role_arn }}
      aws_web_identity_token_file: ${{ needs.get-aws-environment.outputs.aws_web_identity_token_file }}
    secrets:
      registry_username: ${{ secrets.HARBOR_CENTREON_PULL_USERNAME }}
      registry_password: ${{ secrets.HARBOR_CENTREON_PULL_TOKEN }}
      rpm_gpg_key: ${{ secrets.RPM_GPG_SIGNING_KEY }}
      rpm_gpg_signing_key_id: ${{ secrets.RPM_GPG_SIGNING_KEY_ID }}
      rpm_gpg_signing_passphrase: ${{ secrets.RPM_GPG_SIGNING_PASSPHRASE }}
      jira_base_url: ${{ secrets.JIRA_BASE_URL }}
      jira_user_email: ${{ secrets.XRAY_JIRA_USER_EMAIL }}
      jira_api_token: ${{ secrets.XRAY_JIRA_TOKEN }}

  deliver-deb:
    if: |
      needs.changes.outputs.trigger_delivery == 'true' &&
      needs.get-environment.outputs.skip_workflow == 'false' &&
      contains(fromJson('["unstable", "testing"]'), needs.get-environment.outputs.stability) &&
      ! cancelled() &&
      ! contains(needs.*.result, 'failure') &&
      ! contains(needs.*.result, 'cancelled') &&
      github.repository == 'centreon/centreon-collect'

    needs: [get-environment, changes, package]
    runs-on: centreon-common
    strategy:
      fail-fast: false
      matrix:
        include:
          - distrib: trixie
            arch: amd64
          - distrib: trixie
            arch: arm64

    name: deliver ${{ matrix.distrib }} ${{ matrix.arch }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Publish DEB packages
        uses: ./.github/actions/deb-delivery
        with:
          module_name: collect
          distrib: ${{ matrix.distrib }}
          version: ${{ needs.get-environment.outputs.major_version }}
          artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
          cache_key: ${{ github.run_id }}-${{ github.sha }}-deb-centreon-collect-${{ matrix.distrib }}-${{ matrix.arch }}-${{ github.head_ref || github.ref_name }}
          stability: ${{ needs.get-environment.outputs.stability }}
          release_type: ${{ needs.get-environment.outputs.release_type }}
          is_cloud: ${{ needs.get-environment.outputs.is_cloud }}
