name: docker-packaging

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
    paths:
      - '.github/docker/Dockerfile.packaging-*'
      - 'vcpkg.json'
  pull_request:
    paths:
      - '.github/docker/Dockerfile.packaging-*'
      - 'vcpkg.json'

jobs:
  get-environment:
    if: github.repository == 'centreon/centreon-collect'
    uses: ./.github/workflows/get-environment.yml
    with:
      version_file: CMakeLists.txt

  dockerize:
    needs: [get-environment]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable'

    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: centreon-collect
            distrib: alma8
          - runner: centreon-collect
            distrib: alma9
          - runner: centreon-collect
            distrib: bookworm
          - runner: centreon-collect-arm64
            distrib: bookworm
          - runner: centreon-collect
            distrib: bullseye
          - runner: centreon-collect-arm64
            distrib: bullseye
          - runner: centreon-collect
            distrib: jammy
          - runner: centreon-collect-arm64
            distrib: jammy
          - runner: centreon-collect
            distrib: noble

    runs-on: ${{ matrix.runner }}

    name: build docker image ${{ matrix.distrib }} ${{ contains(matrix.runner, 'arm') && ' arm' || '' }}

    env:
      IMAGE_BASE_NAME: packaging-centreon-collect
      IMAGE_SUFFIX: ${{ contains(matrix.runner, 'arm') && '-arm64' || '' }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Login to Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}
          username: ${{ secrets.HARBOR_CENTREON_PUSH_USERNAME }}
          password: ${{ secrets.HARBOR_CENTREON_PUSH_TOKEN }}

      - uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
        with:
          driver-opts: image=${{ vars.DOCKER_PROXY_REGISTRY_URL }}/moby/buildkit:buildx-stable-1

      - name: Build image ${{ env.IMAGE_BASE_NAME }}-${{ matrix.distrib }}${{ env.IMAGE_SUFFIX }}:${{ needs.get-environment.outputs.packaging_img_version }}
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_CHECKS_ANNOTATIONS: false
        with:
          file: .github/docker/Dockerfile.${{ env.IMAGE_BASE_NAME }}-${{ matrix.distrib }}
          context: .
          target: centreon_collect_packaging
          build-args: |
            "REGISTRY_URL=${{ vars.DOCKER_PROXY_REGISTRY_URL }}"
            "TRIPLET=${{ contains(matrix.runner, 'arm') && 'arm64-linux' || 'x64-linux' }}"
          platforms: ${{ contains(matrix.runner, 'arm') && 'linux/arm64' || 'linux/amd64' }}
          pull: true
          push: true
          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ env.IMAGE_BASE_NAME }}-${{ matrix.distrib }}${{ env.IMAGE_SUFFIX }}:${{ needs.get-environment.outputs.packaging_img_version }}

      - name: Build image ${{ env.IMAGE_BASE_NAME }}-vcpk-${{ matrix.distrib }}${{ env.IMAGE_SUFFIX }}:${{ needs.get-environment.outputs.packaging_img_version }}
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6.13.0
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_CHECKS_ANNOTATIONS: false
        with:
          file: .github/docker/Dockerfile.${{ env.IMAGE_BASE_NAME }}-${{ matrix.distrib }}
          context: .
          target: centreon_collect_packaging_vcpkg
          build-args: |
            "REGISTRY_URL=${{ vars.DOCKER_PROXY_REGISTRY_URL }}"
            "TRIPLET=${{ contains(matrix.runner, 'arm') && 'arm64-linux' || 'x64-linux' }}"
          platforms: ${{ contains(matrix.runner, 'arm') && 'linux/arm64' || 'linux/amd64' }}
          pull: false
          push: true
          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ env.IMAGE_BASE_NAME }}-vcpkg-${{ matrix.distrib }}${{ env.IMAGE_SUFFIX }}:${{ needs.get-environment.outputs.packaging_img_version }}

  set-skip-label:
    needs: [get-environment, dockerize]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      ! cancelled() &&
      ! contains(needs.*.result, 'failure') &&
      ! contains(needs.*.result, 'cancelled')
    uses: ./.github/workflows/set-pull-request-skip-label.yml
