name: gorgone

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      unit_tests:
        description: 'Execute the unit tests'
        required: true
        default: true
        type: boolean
  pull_request:
    # paths:
    #   - ".version"
    #   - ".version.centreon-gorgone"
    #   - "gorgone/**"
    #   - "perl-libs/**"
  push:
    branches:
      - develop
      - dev-[2-9][0-9].[0-9][0-9].x
      - master
      - "[2-9][0-9].[0-9][0-9].x"
      - 'release-[2-9][0-9].[0-9][0-9]-next'
      - 'hotfix-[2-9][0-9].[0-9][0-9]-next'
    paths:
      - ".version"
      - ".version.centreon-gorgone"
      - "gorgone/**"
      - "perl-libs/**"
    tags:
      - "centreon-gorgone-*"

env:
  base_directory: gorgone

jobs:
  get-environment:
    uses: ./.github/workflows/get-environment.yml
    with:
      version_file: .version.centreon-gorgone

  changes:
    needs: [get-environment]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable'
    runs-on: ubuntu-24.04
    outputs:
      trigger_delivery: ${{ steps.filter.outputs.trigger_delivery || 'true' }}
      trigger_unit_tests: ${{ steps.filter.outputs.trigger_unit_tests || 'true' }}
      trigger_robot_tests: ${{ steps.filter.outputs.trigger_robot_tests || 'true' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        if: |
          github.event_name == 'pull_request' &&
          needs.get-environment.outputs.stability != 'testing'
        with:
          base: ${{ github.head_ref || github.ref_name }}
          filters: |
            trigger_unit_tests:
              - 'gorgone/**'
              - 'perl-libs/**'
            trigger_robot_tests:
              - 'gorgone/!(tests)/**'
              - 'gorgone/tests/robot/**'
              - 'perl-libs/**'
              - '.github/**'
            trigger_delivery:
              - 'gorgone/!(tests)/**'
              - 'perl-libs/!(lib)/**'
              - 'perl-libs/lib/!(t)/**'
              - 'perl-libs/*'
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  # unit-test-perl:
  #   needs: [get-environment, changes]
  #   if: |
  #     needs.get-environment.outputs.skip_workflow == 'false' &&
  #     needs.get-environment.outputs.stability != 'stable' &&
  #     (github.event.inputs.unit_tests == 'true' || needs.changes.outputs.trigger_unit_tests == 'true')
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       image: [unit-tests-alma8, unit-tests-alma9, unit-tests-bookworm]
  #       include:
  #         - runner_name: ubuntu-24.04
  #         - package_extension: rpm
  #           image: unit-tests-alma8
  #           distrib: el8
  #         - package_extension: rpm
  #           image: unit-tests-alma9
  #           distrib: el9
  #         - package_extension: deb
  #           image: unit-tests-bookworm
  #           distrib: bookworm
  #   runs-on: ${{ matrix.runner_name }}
  #   container:
  #     image: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.image }}
  #     credentials:
  #       username: ${{ secrets.HARBOR_CENTREON_PULL_USERNAME }}
  #       password: ${{ secrets.HARBOR_CENTREON_PULL_TOKEN }}

  #   services:
  #     mariadb:
  #       image: mariadb:10.11
  #       ports:
  #         - 3306
  #       env:
  #         MYSQL_USER: centreon
  #         MYSQL_PASSWORD: password
  #         MYSQL_ROOT_PASSWORD: password

  #   steps:
  #     - name: Get linked branch of centreon repository
  #       id: centreon_repo_linked_branch
  #       run: |
  #         CENTREON_REPO_LINKED_BRANCH=$(git ls-remote -h https://github.com/centreon/centreon.git | grep -E "refs/heads/dev-${{ needs.get-environment.outputs.major_version }}\.x$" >/dev/null 2>&1 && echo "dev-${{ needs.get-environment.outputs.major_version }}.x" || echo develop)

  #         GIT_BRANCH_EXISTS=$(git ls-remote -h https://github.com/centreon/centreon.git | grep -E "refs/heads/${{ github.head_ref || github.ref_name }}$" >/dev/null 2>&1 && echo yes || echo no)
  #         if [[ "$GIT_BRANCH_EXISTS" == "yes" ]]; then
  #           CENTREON_REPO_LINKED_BRANCH="${{ github.head_ref || github.ref_name }}"
  #         fi

  #         echo "linked_branch=$CENTREON_REPO_LINKED_BRANCH" >> $GITHUB_OUTPUT
  #       shell: bash

  #     - name: Checkout sources
  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

  #     - name: Checkout sources
  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  #       with:
  #         repository: centreon/centreon
  #         path: centreon
  #         ref: ${{ steps.centreon_repo_linked_branch.outputs.linked_branch }}
  #         sparse-checkout: |
  #           centreon/www/install/createTables.sql
  #           centreon/www/install/createTablesCentstorage.sql

  #     - name: wait mariadb initialization before creating databases
  #       run: |
  #         hostname=mariadb
  #         max_attempts=20
  #         attempt_num=1
  #         echo "trying to access the database at $hostname"
  #         set +e
  #         while [ $attempt_num -le $max_attempts ]; do
  #           output=$(mysql -h "$hostname" -u root -ppassword -e "SELECT 1;" 2>&1)
  #           status=$?
  #           if [ $status -eq 0 ]; then
  #             echo "Attempt $attempt_num succeeded. Database is accessible."
  #             exit 0
  #           fi
  #           echo "Attempt $attempt_num failed. Trying again in one second..."
  #           sleep 1
  #           attempt_num=$(( attempt_num + 1 ))
  #         done
  #         echo "failed accessing the database at $hostname after $max_attempts attempts : $output"
  #         exit 1

  #     - name: Create databases
  #       run: |
  #         mysql -h mariadb -u root -ppassword -e "CREATE DATABASE \`centreon\`"
  #         mysql -h mariadb -u root -ppassword -e "CREATE DATABASE \`centreon-storage\`"
  #         mysql -h mariadb -u root -ppassword -e "GRANT ALL PRIVILEGES ON centreon.* TO 'centreon'@'%'"
  #         mysql -h mariadb -u root -ppassword -e "GRANT ALL PRIVILEGES ON  \`centreon-storage\`.* TO 'centreon'@'%'"
  #         mysql -h mariadb -u root -ppassword 'centreon' < centreon/centreon/www/install/createTables.sql
  #         mysql -h mariadb -u root -ppassword 'centreon-storage' < centreon/centreon/www/install/createTablesCentstorage.sql

  #     - name: Run unit tests
  #       run: yath -L test ./perl-libs/lib/ ./gorgone/tests/unit/

  #     - name: Upload logs as artifacts if tests failed
  #       if: failure()
  #       uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
  #       with:
  #         name: centreon-collect-perl-unit-tests-${{ matrix.distrib }}
  #         path: ./lastlog.jsonl
  #         retention-days: 1

  package:
    needs: [get-environment]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable'

    strategy:
      fail-fast: false
      matrix:
        include:
          - package_extension: rpm
            image: packaging-centreon-collect-alma8
            distrib: el8
          - package_extension: rpm
            image: packaging-centreon-collect-alma9
            distrib: el9
          - package_extension: deb
            image: packaging-centreon-collect-bookworm
            distrib: bookworm
          # No ubuntu in 24.10, 24.11 or later for now

    runs-on: ubuntu-24.04

    container:
      image: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/${{ matrix.image }}:${{ needs.get-environment.outputs.packaging_img_version }}
      credentials:
        username: ${{ secrets.HARBOR_CENTREON_PULL_USERNAME }}
        password: ${{ secrets.HARBOR_CENTREON_PULL_TOKEN }}

    name: package ${{ matrix.distrib }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set package version and paths according to distrib
        run: |
          if [[ "${{ matrix.package_extension }}" == "deb" ]]; then
            PERL_VENDORLIB="/usr/share/perl5"
          else
            PERL_VENDORLIB="/usr/share/perl5/vendor_perl"
          fi
          echo "PERL_VENDORLIB=$PERL_VENDORLIB" >> $GITHUB_ENV
        shell: bash

      - name: Generate selinux binaries
        if: ${{ matrix.package_extension == 'rpm' }}
        run: |
          cd gorgone/selinux
          sed -i "s/@VERSION@/${{ needs.get-environment.outputs.major_version }}.${{ needs.get-environment.outputs.minor_version }}/g" centreon-gorgoned.te
          make -f /usr/share/selinux/devel/Makefile
        shell: bash

      - name: Remove selinux packaging files on debian
        if: ${{ matrix.package_extension == 'deb' }}
        run: rm -f gorgone/packaging/*-selinux.yaml
        shell: bash

      - name: Package
        uses: ./.github/actions/package
        with:
          nfpm_file_pattern: "gorgone/packaging/*.yaml perl-libs/packaging/*.yaml"
          module_name: "centreon-gorgone"
          distrib: ${{ matrix.distrib }}
          package_extension: ${{ matrix.package_extension }}
          major_version: ${{ needs.get-environment.outputs.major_version }}
          minor_version: ${{ needs.get-environment.outputs.minor_version }}
          release: ${{ needs.get-environment.outputs.release }}
          arch: all
          commit_hash: ${{ github.sha }}
          cache_key: ${{ github.sha }}-${{ github.run_id }}-${{ matrix.package_extension }}-${{ matrix.distrib }}
          rpm_gpg_key: ${{ secrets.RPM_GPG_SIGNING_KEY }}
          rpm_gpg_signing_key_id: ${{ secrets.RPM_GPG_SIGNING_KEY_ID }}
          rpm_gpg_signing_passphrase: ${{ secrets.RPM_GPG_SIGNING_PASSPHRASE }}
          stability: ${{ needs.get-environment.outputs.stability }}
          upload_artifacts: ${{ needs.get-environment.outputs.is_nightly == 'true' || contains(needs.get-environment.outputs.labels, 'upload-artifacts') && 'true' || 'false' }}

  dockerize:
    needs: [get-environment, package]
    if: |
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable'
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        distrib: [alma8]
    name: dockerize ${{ matrix.distrib }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Login to registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}
          username: ${{ secrets.HARBOR_CENTREON_PUSH_USERNAME }}
          password: ${{ secrets.HARBOR_CENTREON_PUSH_TOKEN }}

      - name: Parse distrib name
        id: parse-distrib
        uses: ./.github/actions/parse-distrib
        with:
          distrib: ${{ matrix.distrib }}

      - name: get cached gorgone and perl-libs package
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ./*.${{ steps.parse-distrib.outputs.package_extension }}
          key: ${{ github.sha }}-${{ github.run_id }}-${{ steps.parse-distrib.outputs.package_extension }}-${{ steps.parse-distrib.outputs.package_extension == 'rpm' && steps.parse-distrib.outputs.distrib_family || steps.parse-distrib.outputs.distrib_name }}
          fail-on-cache-miss: true

      - run: |
          mkdir packages-centreon-gorgone
          mv *.${{ steps.parse-distrib.outputs.package_extension }} packages-centreon-gorgone/
        shell: bash

      - name: Get linked branch of centreon repository
        id: centreon_repo_linked_branch
        run: |
          CENTREON_REPO_LINKED_BRANCH=$(git ls-remote -h https://github.com/centreon/centreon.git | grep -E "refs/heads/dev-${{ needs.get-environment.outputs.major_version }}\.x$" >/dev/null 2>&1 && echo "dev-${{ needs.get-environment.outputs.major_version }}.x" || echo develop)

          GIT_BRANCH_EXISTS=$(git ls-remote -h https://github.com/centreon/centreon.git | grep -E "refs/heads/${{ github.head_ref || github.ref_name }}$" >/dev/null 2>&1 && echo yes || echo no)
          if [[ "$GIT_BRANCH_EXISTS" == "yes" ]]; then
            CENTREON_REPO_LINKED_BRANCH="${{ github.head_ref || github.ref_name }}"
          fi

          echo "linked_branch=$CENTREON_REPO_LINKED_BRANCH" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: centreon/centreon
          path: centreon
          ref: ${{ steps.centreon_repo_linked_branch.outputs.linked_branch }}
          sparse-checkout: |
            centreon/www/install/createTables.sql
            centreon/www/install/createTablesCentstorage.sql

      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Docker build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        env:
          DOCKER_BUILD_CHECKS_ANNOTATIONS: false
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          file: .github/docker/Dockerfile.gorgone-testing-${{ matrix.distrib }}
          build-args: |
            "VERSION=${{ needs.get-environment.outputs.major_version }}"
            "IS_CLOUD=${{ needs.get-environment.outputs.is_cloud }}"
          secrets: |
            "ARTIFACTORY_INTERNAL_REPO_USERNAME=${{ secrets.ARTIFACTORY_INTERNAL_REPO_USERNAME }}"
            "ARTIFACTORY_INTERNAL_REPO_PASSWORD=${{ secrets.ARTIFACTORY_INTERNAL_REPO_PASSWORD }}"
          pull: true
          push: true
          load: true
          tags: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/gorgone-testing-${{ matrix.distrib }}:${{ github.head_ref || github.ref_name }}

      - name: Store image in local archive
        run: |
          docker tag ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/gorgone-testing-${{ matrix.distrib }}:${{ github.head_ref || github.ref_name }} gorgone-testing-${{ matrix.distrib }}:${{ github.head_ref || github.ref_name }}
          mkdir -p docker-image
          docker save --output ./docker-image/gorgone-testing-${{ matrix.distrib }}.tar gorgone-testing-${{ matrix.distrib }}:${{ github.head_ref || github.ref_name }}
        shell: bash

      - name: Clear previous docker image from cache
        run: |
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/centreon/centreon-collect/actions/caches?key=docker-image-gorgone-testing-${{ matrix.distrib }}-${{ github.head_ref || github.ref_name }}
        shell: bash

      - name: Store slim image in cache
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ./docker-image
          key: docker-image-gorgone-testing-${{ matrix.distrib }}-${{ github.head_ref || github.ref_name }}

  robot-test-list:
    needs: [get-environment, changes, dockerize]
    if: |
      github.repository == 'centreon/centreon-collect' &&
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable' &&
      needs.changes.outputs.trigger_robot_tests == 'true'
    runs-on: ubuntu-24.04
    outputs:
      features: ${{ steps.list-features.outputs.features }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: List features
        id: list-features
        run: |
          cd gorgone/tests/robot/tests
          echo "features=$(grep -Rl '*** Test Cases ***' . | grep '.robot' | sed -e "s#^./##" | sort | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  robot-test-run:
    needs: [get-environment, changes, robot-test-list]
    if: |
      github.repository == 'centreon/centreon-collect' &&
      needs.get-environment.outputs.skip_workflow == 'false' &&
      needs.get-environment.outputs.stability != 'stable' &&
      needs.changes.outputs.trigger_robot_tests == 'true'

    strategy:
      fail-fast: false
      matrix:
        # distrib: [el8, el9, bookworm]  # No ubuntu in 24.10, 24.11 or later for now
        feature: ${{ fromJson(needs.robot-test-list.outputs.features) }}
        distrib: [alma8]

    runs-on: ubuntu-24.04
    name: ${{ matrix.feature }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Parse distrib name
        id: parse-distrib
        uses: ./.github/actions/parse-distrib
        with:
          distrib: ${{ matrix.distrib }}

      - name: Restore gorgone image from cache
        id: cache-docker
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        continue-on-error: true
        timeout-minutes: 6
        with:
          path: ./docker-image
          key: docker-image-gorgone-testing-${{ matrix.distrib }}-${{ github.head_ref || github.ref_name }}
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5

      - name: Load gorgone image
        if: ${{ steps.cache-docker.outputs.cache-hit == 'true' }}
        run: |
          docker load --input ./docker-image/gorgone-testing-${{ matrix.distrib }}.tar
          docker tag gorgone-testing-${{ matrix.distrib }}:${{ github.head_ref || github.ref_name }} ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/gorgone-testing-${{ matrix.distrib }}:${{ github.head_ref || github.ref_name }}
        shell: bash

      - name: Replace / with - in the feature path
        id: feature-path
        if: always()
        run: |
          feature_name="${{ matrix.feature }}"
          feature_name_with_dash="${feature_name//\//-}"
          echo "Modified Feature Name: $feature_name_with_dash"
          echo "feature_name_with_dash=$feature_name_with_dash" >> $GITHUB_OUTPUT

      - name: ${{ format('Test {0}', matrix.feature) }}
        env:
          GORGONE_IMAGE: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/gorgone-testing-${{ matrix.distrib }}:${{ github.head_ref || github.ref_name }}
          FEATURE: gorgone/tests/robot/tests/${{ matrix.feature }}
        run: |
          docker compose -f ./.github/docker/docker-compose.yml up --exit-code-from gorgone
        timeout-minutes: 30
        shell: bash

      - name: Get gorgone container logs
        if: failure()
        env:
          GORGONE_IMAGE: ${{ vars.DOCKER_INTERNAL_REGISTRY_URL }}/gorgone-testing-${{ matrix.distrib }}:${{ github.head_ref || github.ref_name }}
          FEATURE: gorgone/tests/robot/tests/${{ matrix.feature }}
        run: |
          mkdir -p /tmp/gorgone-debug/${{ steps.feature-path.outputs.feature_name_with_dash }}
          docker compose -f ./.github/docker/docker-compose.yml cp gorgone:/test_gorgone/log.html /tmp/gorgone-debug/${{ steps.feature-path.outputs.feature_name_with_dash }}/log.html
          docker compose -f ./.github/docker/docker-compose.yml cp gorgone:/var/log/centreon-gorgone /tmp/gorgone-debug/${{ steps.feature-path.outputs.feature_name_with_dash }}/log
          docker compose -f ./.github/docker/docker-compose.yml cp gorgone:/etc/centreon-gorgone /tmp/gorgone-debug/${{ steps.feature-path.outputs.feature_name_with_dash }}/etc

      - name: Upload gorgone and robot debug artifacts
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: gorgone-debug-${{ matrix.distrib }}-${{ steps.feature-path.outputs.feature_name_with_dash }}
          path: |
            /tmp/gorgone-debug
          retention-days: 1

  robot-test-report:
    needs: [robot-test-run]
    if: ${{ !cancelled() }}
    strategy:
      fail-fast: false
      matrix:
        distrib: [alma8]
    runs-on: ubuntu-24.04
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        if: ${{ contains(needs.robot-test-run.result, 'failure') }}
        with:
          name: gorgone-debug-${{ matrix.distrib }}
          pattern: gorgone-debug-${{ matrix.distrib }}-*
          retention-days: 1

      - name: Delete merged artifacts
        uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b # v5.1.0
        with:
          name: gorgone-debug-${{ matrix.distrib }}-*
          failOnError: false

  # deliver-sources:
  #   runs-on: centreon-common
  #   needs: [get-environment, package]
  #   if: |
  #     github.event_name != 'workflow_dispatch' &&
  #     needs.get-environment.outputs.stability == 'stable' &&
  #     ! cancelled() &&
  #     ! contains(needs.*.result, 'failure') &&
  #     ! contains(needs.*.result, 'cancelled')

  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

  #     - name: Deliver sources
  #       uses: ./.github/actions/release-sources
  #       with:
  #         bucket_directory: centreon-gorgone
  #         module_directory: gorgone
  #         module_name: centreon-gorgone
  #         major_version: ${{ needs.get-environment.outputs.major_version }}
  #         minor_version: ${{ needs.get-environment.outputs.minor_version }}
  #         token_download_centreon_com: ${{ secrets.TOKEN_DOWNLOAD_CENTREON_COM }}

  # deliver-rpm:
  #   runs-on: centreon-common
  #   needs: [get-environment, unit-test-perl, robot-test-gorgone, changes]
  #   if: |
  #     needs.get-environment.outputs.skip_workflow == 'false' &&
  #     needs.changes.outputs.trigger_delivery == 'true' &&
  #     ((needs.get-environment.outputs.delivery_type == 'feature' && contains(github.event.pull_request.labels.*.name, 'delivery-feature')) ||
  #     contains(fromJson('["testing", "unstable"]'), needs.get-environment.outputs.stability)) &&
  #     ! cancelled() &&
  #     ! contains(needs.*.result, 'failure') &&
  #     ! contains(needs.*.result, 'cancelled')

  #   strategy:
  #     matrix:
  #       distrib: [el8, el9]

  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

  #     - name: Delivery
  #       uses: ./.github/actions/rpm-delivery
  #       with:
  #         module_name: gorgone
  #         distrib: ${{ matrix.distrib }}
  #         version: ${{ needs.get-environment.outputs.major_version }}
  #         artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
  #         cache_key: ${{ github.sha }}-${{ github.run_id }}-rpm-${{ matrix.distrib }}
  #         stability: ${{ needs.get-environment.outputs.stability }}
  #         release_type: ${{ needs.get-environment.outputs.release_type }}
  #         is_cloud: ${{ needs.get-environment.outputs.is_cloud }}
  #         delivery_type: ${{ needs.get-environment.outputs.delivery_type }}
  #         centreon_technique_pat: ${{ secrets.CENTREON_TECHNIQUE_PAT }}

  # deliver-deb:
  #   runs-on: centreon-common
  #   needs: [get-environment, unit-test-perl, robot-test-gorgone, changes]
  #   if: |
  #     needs.get-environment.outputs.skip_workflow == 'false' &&
  #     needs.changes.outputs.trigger_delivery == 'true' &&
  #     contains(fromJson('["unstable", "testing"]'), needs.get-environment.outputs.stability) &&
  #     ! cancelled() &&
  #     ! contains(needs.*.result, 'failure') &&
  #     ! contains(needs.*.result, 'cancelled') &&
  #     (needs.get-environment.outputs.is_cloud == 'false' || needs.get-environment.outputs.stability == 'unstable')

  #   strategy:
  #     matrix:
  #       distrib: [bookworm]  # No ubuntu in 24.10, 24.11 or later for now

  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

  #     - name: Delivery
  #       uses: ./.github/actions/deb-delivery
  #       with:
  #         module_name: gorgone
  #         distrib: ${{ matrix.distrib }}
  #         version: ${{ needs.get-environment.outputs.major_version }}
  #         artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
  #         cache_key: ${{ github.sha }}-${{ github.run_id }}-deb-${{ matrix.distrib }}
  #         stability: ${{ needs.get-environment.outputs.stability }}
  #         release_type: ${{ needs.get-environment.outputs.release_type }}
  #         is_cloud: ${{ needs.get-environment.outputs.is_cloud }}

  # promote:
  #   needs: [get-environment, deliver-rpm, deliver-deb]
  #   if: |
  #     needs.get-environment.outputs.skip_workflow == 'false' &&
  #     (contains(fromJson('["stable", "testing"]'), needs.get-environment.outputs.stability) && github.event_name != 'workflow_dispatch') &&
  #     ! cancelled() &&
  #     ! contains(needs.*.result, 'failure') &&
  #     ! contains(needs.*.result, 'cancelled') &&
  #     github.repository == 'centreon/centreon-collect'

  #   runs-on: centreon-common
  #   strategy:
  #     matrix:
  #       distrib: [el8, el9, bookworm]

  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

  #     - name: Promote ${{ matrix.distrib }} to stable
  #       uses: ./.github/actions/promote-to-stable
  #       with:
  #         artifactory_token: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
  #         module_name: gorgone
  #         distrib: ${{ matrix.distrib }}
  #         major_version: ${{ needs.get-environment.outputs.major_version }}
  #         minor_version: ${{ needs.get-environment.outputs.minor_version }}
  #         stability: ${{ needs.get-environment.outputs.stability }}
  #         github_ref_name: ${{ github.ref_name }}
  #         release_type: ${{ needs.get-environment.outputs.release_type }}
  #         is_cloud: ${{ needs.get-environment.outputs.is_cloud }}

  # set-skip-label:
  #   needs: [get-environment, deliver-rpm, deliver-deb, promote]
  #   if: |
  #     needs.get-environment.outputs.skip_workflow == 'false' &&
  #     ! cancelled() &&
  #     ! contains(needs.*.result, 'failure') &&
  #     ! contains(needs.*.result, 'cancelled')
  #   uses: ./.github/workflows/set-pull-request-skip-label.yml
