---
name: Sync next major stable and dev version branches

on:
  pull_request:
    types:
      - closed
    branches:
      - "master"
  workflow_dispatch:

jobs:
  main:
    name: Sync Stable Branches
    runs-on: ubuntu-24.04
    if: github.event.pull_request.merged == true && github.repository == 'centreon/centreon-collect'
    steps:
      - name: git checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.CENTREON_TECHNIQUE_PAT }}

      - name: Sync Branches
        id: release
        uses: ./.github/actions/sync-branches
        with:
          src_branch: master
          dest_branch: develop
