---
name: Sync next major stable and dev version branches

on:
  pull_request_target:
    types:
      - closed
    branches:
      - "master"
  workflow_dispatch:

jobs:
  main:
    name: Sync Stable Branches
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true
    steps:
      - name: git checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
          token: ${{ secrets.CENTREON_TECHNIQUE_PAT }}

      - name: Sync Branches
        id: release
        uses: ./.github/actions/sync-branches
        with:
          src_branch: master
          dest_branch: develop
