---
name: release-trigger-builds

on:
  workflow_dispatch:
    inputs:
      dispatch_target_release_branch:
        description: "Release or hotfix branch to trigger"
        required: true
      dispatch_content:
        description: "Dispatch content (what workflow is going to be triggered)"
        required: true
        type: choice
        options:
          - REGULAR # Centreon components only without libs
          - CHANGED_ONLY # Anything that received a change
          - FULL # Centreon components + libs

jobs:
  release-trigger-builds:
    if: github.repository == 'centreon/centreon-collect'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          token: ${{ secrets.CENTREON_TECHNIQUE_PAT }}

      - name: Install Github CLI
        run: |
          set -eux
          if ! command -v gh &> /dev/null; then
            echo "Installing GH CLI."
            type -p curl >/dev/null || (sudo apt-get update && sudo apt-get install curl -y)
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt-get update
            sudo apt-get install gh -y
          else
            echo "GH CLI is already installed."
          fi
        shell: bash

      - name: Create requested release/hotfix branch
        run: |
          set -eux

          # VARS
          OWNER="centreon"
          REPO="centreon-collect"
          NEW_BRANCH="${{ inputs.dispatch_target_release_branch }}" #Possible valid values release-29.10-next or hotfix-29.10-next
          BASE_REF=""
          RELEASE_BRANCH_MAJOR_VERSION=""
          RELEASE_SCOPE=""
          RELEASE_TYPE=""
          PREVIOUS_RELEASE_BUNDLE_TAG=""

          # Extract RELEASE_BRANCH_MAJOR_VERSION
          RELEASE_BRANCH_MAJOR_VERSION="$(echo ${{ inputs.dispatch_target_release_branch }} | cut -d "-" -f2)"
          echo "Major version detected: $RELEASE_BRANCH_MAJOR_VERSION"

          #Deduce RELEASE_SCOPE from RELEASE_BRANCH_MAJOR_VERSION
          if [[ "$RELEASE_BRANCH_MAJOR_VERSION" =~ ^[0-9]{2}\.(04|10)$ ]]; then
            RELEASE_SCOPE="onprem"
            echo "Release scope detected: onprem"
          elif [[ ! "$RELEASE_BRANCH_MAJOR_VERSION" =~ ^[0-9]{2}\.(04|10)$ ]]; then
            RELEASE_SCOPE="cloud"
            echo "Release scope detected: cloud"
          else
            echo "Invalid release branch major version: $RELEASE_BRANCH_MAJOR_VERSION. Either RELEASE_BRANCH is invalid or version in it is invalid."
            exit 1
          fi

          # Set RELEASE_TYPE based on dispatch_target_release_branch prefix (release or hotfix)
          RELEASE_TYPE="$(echo ${{ inputs.dispatch_target_release_branch }} | cut -d "-" -f1)"
          echo "Release type detected: $RELEASE_TYPE"

          # Get previous stable release bundle tags
          # Previous release bundle tag
          if [[ "$RELEASE_SCOPE" == "cloud" ]]; then
            PREVIOUS_STABLE_BUNDLE_TAG=$(git tag -l --sort=-version:refname "release-cloud-*-${RELEASE_BRANCH_MAJOR_VERSION}" | head -n 1)
          elif [[ "$RELEASE_SCOPE" == "onprem" ]]; then
            PREVIOUS_STABLE_BUNDLE_TAG=$(git tag -l --sort=-version:refname "release-onprem-*-${RELEASE_BRANCH_MAJOR_VERSION}" | head -n 1)
          else
            echo "Invalid release_scope: $RELEASE_SCOPE"
          fi

          # Check if a tag was found
          if [ -z "$PREVIOUS_STABLE_BUNDLE_TAG" ]; then
            echo "Previous stable bundle tag not found: $PREVIOUS_STABLE_BUNDLE_TAG"
            exit 1
          else
            echo "Previous stable bundle tag found: $PREVIOUS_STABLE_BUNDLE_TAG"
          fi

          # Setting BASE_REF based on RELEASE_BRANCH_MAJOR_VERSION in dispatch_target_release_branch
          if RELEASE_TYPE is release AND RELEASE_SCOPE is cloud => create from develop + use version XX.YY of dispatch_target_release_branch
          if [[ "$RELEASE_TYPE" == "release" && "$RELEASE_SCOPE" == "cloud" ]]; then
            echo "Release type detected: $RELEASE_TYPE with release scope: $RELEASE_SCOPE"
            BASE_REF="develop"

          # if RELEASE_TYPE is release => create from dev-XX.YY.x + use version XX.YY of dispatch_target_release_branch
          elif [[ "$RELEASE_TYPE" == "release" ]]; then
            echo "Release type detected: $RELEASE_TYPE with release scope: $RELEASE_SCOPE"
            BASE_REF="dev-$RELEASE_BRANCH_MAJOR_VERSION.x"

          # if RELEASE_TYPE is hotfix => create from latest stable bundle tag + use version XX.YY of dispatch_target_release_branch
          # bundle tag format is "release-<scope>-YYYYMMNN-XX.YY" with
          # YYYY is a year (ex: 2029)
          # MM is a month (ex: 01)
          # XX.YY is a major version (ex: 29.10)
          elif [[ "$RELEASE_TYPE" == "hotfix" ]]; then
            echo "Release type detected: $RELEASE_TYPE with release scope: $RELEASE_SCOPE"
            BASE_REF="$PREVIOUS_STABLE_BUNDLE_TAG"

          else
            echo "Either $RELEASE_TYPE or $RELEASE_SCOPE or $RELEASE_BRANCH_MAJOR_VERSION were not valid combination."
            exit 1
          fi

          # Creating NEW_BRANCH from BASE_REF
          # Check if NEW_BRANCH already exists and exit with error if it does
          echo "Checking if $NEW_BRANCH already exists."
          # Create the NEW_BRANCH
          echo "Creating requested release/hotfix branch with name $NEW_BRANCH."

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger selected branches
        run: |
          set -eux

          # VARS
          # names defined in workflow files per components
          # these are the default component_list values, they can be overriden further in the code
          #COMPONENTS_OSS=("awie" "dsm" "gorgone" "ha" "open-tickets" "web")
          #COMPONENTS_OSS_FULL=("awie" "dsm" "gorgone" "ha" "open-tickets" "web")
          #COMPONENTS_MODULES=("anomaly-detection" "autodiscovery" "bam" "cloud-business-extensions" "cloud-extensions" "it-edition-extensions" "lm" "map" "mbi" "ppm")
          #COMPONENTS_MODULES_FULL=("anomaly-detection" "autodiscovery" "bam" "cloud-business-extensions" "cloud-extensions" "it-edition-extensions" "lm" "map" "mbi" "ppm" "php-pecl-gnupg" "sourceguardian-loader")
          COMPONENTS_COLLECT_REGULAR=("centreon-collect" "centreon-common" "gorgone" "monitoring-agent")
          COMPONENTS_COLLECT_FULL=("centreon-collect" "centreon-common" "gorgone" "monitoring-agent" "docker-packaging" "docker-collect-testing" "docker-gorgone-testing" "libzmq" "lua-curl")
          RUNS_URL=""

          # Accept the branche types listed below, nothing else
          # release prefixed branches: standard release type (release-xxxxx)
          # hotfix prefixed branches: hotfix release type (hotfix-xxxxx)
          # develop: start of a new major version (not a release) (develop)

          # Build link to list of runs for selected branch
          if [[ ${{ inputs.dispatch_target_release_branch }} =~ ^release-2[0-9]\.[0-9]+-next$ ]] || [[ ${{ inputs.dispatch_target_release_branch }} == "develop" ]] || || [[ ${{ inputs.dispatch_target_release_branch }} =~ ^hotfix-2[0-9]\.[0-9]+-next$ ]];then
            echo "Using ${{ inputs.dispatch_target_release_branch }} as branch to build testing packages."
            RUNS_URL="https://github.com/centreon/centreon-collect/actions?query=branch%3A${{ inputs.dispatch_target_release_branch }}"
          else
            echo "::error::Invalid release branch name selected ${{ inputs.dispatch_target_release_branch }}, please check the release branch name in the input."
            exit 1
          fi

          # Handle the limited cases of dispatch_content
          echo "Requested ${{ inputs.dispatch_content }} content."
          case ${{ inputs.dispatch_content }} in
            "FULL")
            echo "Triggering all components, docker builders, php and extra libs."
            for COMPONENT in "${COMPONENTS_COLLECT_FULL[@]}"; do
              echo "Dispatching trigger to $COMPONENT workflow."
              # gh workflow run "$COMPONENT" -r ${{ inputs.dispatch_target_release_branch }}
            done

            ;;
            "REGULAR")
            echo "Triggering all components only."
            for COMPONENT in "${COMPONENTS_COLLECT[@]}"; do
              echo "Dispatching trigger to $COMPONENT workflow."
              # gh workflow run "$COMPONENT" -r ${{ inputs.dispatch_target_release_branch }}
            done

            ;;
            "CHANGED_ONLY")
            echo "Triggering components that received at least one change."
            ;;
          esac

          echo "Dispatch was successfully triggered. Runs can be found at ${RUNS_URL}"
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
