---
name: Create collect jira version

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
      - "[2-9][0-9].[0-9][0-9].x"
    paths:
      - "centreon-collect/**"
  workflow_dispatch:

env:
  module: "collect"

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Release
        id: release
        uses: ./.github/actions/release
        with:
          jira_token: ${{ secrets.JIRA_TOKEN }}
          jira_project_id: ${{ secrets.JIRA_PROJECT_ID }}
