---
name: Tag centreon collect releases

on:
  pull_request_target:
    types:
      - closed
    branches:
      - "master"
      - "*.x"
      - "!dev*"
    paths:
      - ".github/actions/release/action.yml"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release
        id: release
        uses: ./.github/actions/release
        with:
          jira_token: ${{ secrets.JIRA_TOKEN }}
