name: dependency-scan

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}

on:
  pull_request:
    paths:
      - '**'
      - '!bbdo/**'
      - '!broker/**'
      - '!ccc/**'
      - '!clib/**'
      - '!connectors/**'
      - '!agent/**'
      - '!common/**'
      - '!custom-triplets/**'
      - '!packaging/centreon-monitoring-agent/**'
      - '!engine/**'
      - '!grpc/**'
      - '!packaging/centreon-collect/**'
      - '!overlays/**'
      - '!selinux/centreon-broker/**'
      - '!selinux/centreon-engine/**'
      - '!tests/**'
      - '!gorgone/**'
      - '!perl-libs/**'
      - '!.github/docker/gorgone/**'

  workflow_dispatch:

jobs:
  dependency-scan:
    uses: centreon/security-tools/.github/workflows/dependency-analysis.yml@main
